'use strict';

const ALPHABET_REF_JA = [
  ['あ', 'a'],   ['い', 'i'],   ['う', 'u'],   ['え', 'e'],   ['お', 'o'],
  ['か', 'ka'],  ['き', 'ki'],  ['く', 'ku'],  ['け', 'ke'],  ['こ', 'ko'],
  ['さ', 'sa'],  ['し', 'shi'], ['す', 'su'],  ['せ', 'se'],  ['そ', 'so'],
  ['た', 'ta'],  ['ち', 'chi'], ['つ', 'tsu'], ['て', 'te'],  ['と', 'to'],
  ['な', 'na'],  ['に', 'ni'],  ['ぬ', 'nu'],  ['ね', 'ne'],  ['の', 'no'],
  ['は', 'ha'],  ['ひ', 'hi'],  ['ふ', 'fu'],  ['へ', 'he'],  ['ほ', 'ho'],
  ['ま', 'ma'],  ['み', 'mi'],  ['む', 'mu'],  ['め', 'me'],  ['も', 'mo'],
  ['や', 'ya'],  ['ゆ', 'yu'],  ['よ', 'yo'],
  ['ら', 'ra'],  ['り', 'ri'],  ['る', 'ru'],  ['れ', 're'],  ['ろ', 'ro'],
  ['わ', 'wa'],  ['を', 'wo'],  ['ん', 'n'],
];

const WORDS_JA = [
  // Greetings
  { word: "こんにちは", transliteration: "konnichiwa", alternates: [], english: "hello (daytime)", category: "Greetings" },
  { word: "こんばんは", transliteration: "konbanwa", alternates: [], english: "good evening", category: "Greetings" },
  { word: "おはよう", transliteration: "ohayou", alternates: ["ohayo"], english: "good morning (informal)", category: "Greetings" },
  { word: "おはようございます", transliteration: "ohayou gozaimasu", alternates: ["ohayo gozaimasu"], english: "good morning (formal)", category: "Greetings" },
  { word: "さようなら", transliteration: "sayounara", alternates: ["sayonara"], english: "goodbye", category: "Greetings" },
  { word: "ありがとう", transliteration: "arigatou", alternates: ["arigato"], english: "thank you (informal)", category: "Greetings" },
  { word: "ありがとうございます", transliteration: "arigatou gozaimasu", alternates: ["arigato gozaimasu"], english: "thank you (formal)", category: "Greetings" },
  { word: "すみません", transliteration: "sumimasen", alternates: [], english: "excuse me / I'm sorry", category: "Greetings" },
  { word: "ごめんなさい", transliteration: "gomen nasai", alternates: ["gomennasai"], english: "I'm sorry", category: "Greetings" },
  { word: "はい", transliteration: "hai", alternates: [], english: "yes", category: "Greetings" },
  { word: "いいえ", transliteration: "iie", alternates: ["ie"], english: "no", category: "Greetings" },
  { word: "どうぞ", transliteration: "douzo", alternates: ["dozo"], english: "please / here you go", category: "Greetings" },

  // Numbers
  { word: "いち", transliteration: "ichi", alternates: [], english: "one", category: "Numbers" },
  { word: "に", transliteration: "ni", alternates: [], english: "two", category: "Numbers" },
  { word: "さん", transliteration: "san", alternates: [], english: "three", category: "Numbers" },
  { word: "よん", transliteration: "yon", alternates: ["shi"], english: "four", category: "Numbers" },
  { word: "ご", transliteration: "go", alternates: [], english: "five", category: "Numbers" },
  { word: "ろく", transliteration: "roku", alternates: [], english: "six", category: "Numbers" },
  { word: "なな", transliteration: "nana", alternates: ["shichi"], english: "seven", category: "Numbers" },
  { word: "はち", transliteration: "hachi", alternates: [], english: "eight", category: "Numbers" },
  { word: "きゅう", transliteration: "kyuu", alternates: ["kyu", "ku"], english: "nine", category: "Numbers" },
  { word: "じゅう", transliteration: "juu", alternates: ["ju"], english: "ten", category: "Numbers" },
  { word: "ひゃく", transliteration: "hyaku", alternates: [], english: "one hundred", category: "Numbers" },
  { word: "せん", transliteration: "sen", alternates: [], english: "one thousand", category: "Numbers" },

  // Days
  { word: "げつようび", transliteration: "getsuyoubi", alternates: ["getsuyobi"], english: "Monday", category: "Days" },
  { word: "かようび", transliteration: "kayoubi", alternates: ["kayobi"], english: "Tuesday", category: "Days" },
  { word: "すいようび", transliteration: "suiyoubi", alternates: ["suiyobi"], english: "Wednesday", category: "Days" },
  { word: "もくようび", transliteration: "mokuyoubi", alternates: ["mokuyobi"], english: "Thursday", category: "Days" },
  { word: "きんようび", transliteration: "kin'youbi", alternates: ["kin-youbi", "kinyoubi", "kinyobi"], english: "Friday", category: "Days" },
  { word: "どようび", transliteration: "doyoubi", alternates: ["doyobi"], english: "Saturday", category: "Days" },
  { word: "にちようび", transliteration: "nichiyoubi", alternates: ["nichiyobi"], english: "Sunday", category: "Days" },

  // Months
  { word: "いちがつ", transliteration: "ichigatsu", alternates: [], english: "January", category: "Months" },
  { word: "にがつ", transliteration: "nigatsu", alternates: [], english: "February", category: "Months" },
  { word: "さんがつ", transliteration: "sangatsu", alternates: [], english: "March", category: "Months" },
  { word: "しがつ", transliteration: "shigatsu", alternates: [], english: "April", category: "Months" },
  { word: "ごがつ", transliteration: "gogatsu", alternates: [], english: "May", category: "Months" },
  { word: "ろくがつ", transliteration: "rokugatsu", alternates: [], english: "June", category: "Months" },
  { word: "しちがつ", transliteration: "shichigatsu", alternates: [], english: "July", category: "Months" },
  { word: "はちがつ", transliteration: "hachigatsu", alternates: [], english: "August", category: "Months" },
  { word: "くがつ", transliteration: "kugatsu", alternates: [], english: "September", category: "Months" },
  { word: "じゅうがつ", transliteration: "juugatsu", alternates: ["jugatsu"], english: "October", category: "Months" },
  { word: "じゅういちがつ", transliteration: "juuichigatsu", alternates: ["juichigatsu"], english: "November", category: "Months" },
  { word: "じゅうにがつ", transliteration: "juunigatsu", alternates: ["junigatsu"], english: "December", category: "Months" },

  // Family
  { word: "おかあさん", transliteration: "okaasan", alternates: ["okasan"], english: "mother", category: "Family" },
  { word: "おとうさん", transliteration: "otousan", alternates: ["otosan"], english: "father", category: "Family" },
  { word: "おにいさん", transliteration: "oniisan", alternates: ["onisan"], english: "older brother", category: "Family" },
  { word: "おねえさん", transliteration: "oneesan", alternates: ["onesan"], english: "older sister", category: "Family" },
  { word: "おとうと", transliteration: "otouto", alternates: ["ototo"], english: "younger brother", category: "Family" },
  { word: "いもうと", transliteration: "imouto", alternates: ["imoto"], english: "younger sister", category: "Family" },
  { word: "むすこ", transliteration: "musuko", alternates: [], english: "son", category: "Family" },
  { word: "むすめ", transliteration: "musume", alternates: [], english: "daughter", category: "Family" },
  { word: "おじいさん", transliteration: "ojiisan", alternates: ["ojisan"], english: "grandfather", category: "Family" },
  { word: "おばあさん", transliteration: "obaasan", alternates: ["obasan"], english: "grandmother", category: "Family" },

  // Colors
  { word: "あか", transliteration: "aka", alternates: [], english: "red", category: "Colors" },
  { word: "あお", transliteration: "ao", alternates: [], english: "blue / green", category: "Colors" },
  { word: "みどり", transliteration: "midori", alternates: [], english: "green", category: "Colors" },
  { word: "きいろ", transliteration: "kiiro", alternates: [], english: "yellow", category: "Colors" },
  { word: "しろ", transliteration: "shiro", alternates: [], english: "white", category: "Colors" },
  { word: "くろ", transliteration: "kuro", alternates: [], english: "black", category: "Colors" },
  { word: "オレンジ", transliteration: "orenji", alternates: [], english: "orange", category: "Colors" },
  { word: "むらさき", transliteration: "murasaki", alternates: [], english: "purple", category: "Colors" },
  { word: "ピンク", transliteration: "pinku", alternates: [], english: "pink", category: "Colors" },
  { word: "ちゃいろ", transliteration: "chairo", alternates: [], english: "brown", category: "Colors" },
  { word: "はいいろ", transliteration: "haiiro", alternates: [], english: "gray", category: "Colors" },

  // Food & Drink
  { word: "ごはん", transliteration: "gohan", alternates: [], english: "rice / meal", category: "Food & Drink" },
  { word: "みず", transliteration: "mizu", alternates: [], english: "water", category: "Food & Drink" },
  { word: "ぎゅうにゅう", transliteration: "gyuunyuu", alternates: ["gyunyuu", "gyuunyu"], english: "milk", category: "Food & Drink" },
  { word: "にく", transliteration: "niku", alternates: [], english: "meat", category: "Food & Drink" },
  { word: "さかな", transliteration: "sakana", alternates: [], english: "fish", category: "Food & Drink" },
  { word: "たまご", transliteration: "tamago", alternates: [], english: "egg", category: "Food & Drink" },
  { word: "コーヒー", transliteration: "koohii", alternates: ["kohii", "kohi"], english: "coffee", category: "Food & Drink" },
  { word: "おちゃ", transliteration: "ocha", alternates: [], english: "tea (green tea)", category: "Food & Drink" },
  { word: "ビール", transliteration: "biiru", alternates: ["biru"], english: "beer", category: "Food & Drink" },
  { word: "パン", transliteration: "pan", alternates: [], english: "bread", category: "Food & Drink" },
  { word: "チーズ", transliteration: "chiizu", alternates: ["chiizu"], english: "cheese", category: "Food & Drink" },
  { word: "すし", transliteration: "sushi", alternates: [], english: "sushi", category: "Food & Drink" },
  { word: "ラーメン", transliteration: "raamen", alternates: ["ramen"], english: "ramen noodles", category: "Food & Drink" },
  { word: "てんぷら", transliteration: "tenpura", alternates: ["tempura"], english: "tempura", category: "Food & Drink" },
  { word: "そば", transliteration: "soba", alternates: [], english: "soba noodles", category: "Food & Drink" },
  { word: "うどん", transliteration: "udon", alternates: [], english: "udon noodles", category: "Food & Drink" },
  { word: "りんご", transliteration: "ringo", alternates: [], english: "apple", category: "Food & Drink" },
  { word: "バナナ", transliteration: "banana", alternates: [], english: "banana", category: "Food & Drink" },
  { word: "さとう", transliteration: "satou", alternates: ["sato"], english: "sugar", category: "Food & Drink" },
  { word: "しお", transliteration: "shio", alternates: [], english: "salt", category: "Food & Drink" },

  // Body
  { word: "あたま", transliteration: "atama", alternates: [], english: "head", category: "Body" },
  { word: "かお", transliteration: "kao", alternates: [], english: "face", category: "Body" },
  { word: "め", transliteration: "me", alternates: [], english: "eye", category: "Body" },
  { word: "みみ", transliteration: "mimi", alternates: [], english: "ear", category: "Body" },
  { word: "はな", transliteration: "hana", alternates: [], english: "nose / flower", category: "Body" },
  { word: "くち", transliteration: "kuchi", alternates: [], english: "mouth", category: "Body" },
  { word: "て", transliteration: "te", alternates: [], english: "hand", category: "Body" },
  { word: "あし", transliteration: "ashi", alternates: [], english: "leg / foot", category: "Body" },
  { word: "こころ", transliteration: "kokoro", alternates: [], english: "heart (emotional)", category: "Body" },
  { word: "せなか", transliteration: "senaka", alternates: [], english: "back", category: "Body" },
  { word: "は", transliteration: "ha", alternates: [], english: "tooth", category: "Body" },
  { word: "かみ", transliteration: "kami", alternates: [], english: "hair / god / paper", category: "Body" },

  // Verbs
  { word: "たべる", transliteration: "taberu", alternates: [], english: "to eat", category: "Verbs" },
  { word: "のむ", transliteration: "nomu", alternates: [], english: "to drink", category: "Verbs" },
  { word: "ねる", transliteration: "neru", alternates: [], english: "to sleep", category: "Verbs" },
  { word: "あるく", transliteration: "aruku", alternates: [], english: "to walk", category: "Verbs" },
  { word: "はなす", transliteration: "hanasu", alternates: [], english: "to speak / tell", category: "Verbs" },
  { word: "みる", transliteration: "miru", alternates: [], english: "to see / watch", category: "Verbs" },
  { word: "きく", transliteration: "kiku", alternates: [], english: "to hear / listen", category: "Verbs" },
  { word: "あいする", transliteration: "aisuru", alternates: [], english: "to love", category: "Verbs" },
  { word: "いく", transliteration: "iku", alternates: [], english: "to go", category: "Verbs" },
  { word: "くる", transliteration: "kuru", alternates: [], english: "to come", category: "Verbs" },
  { word: "しる", transliteration: "shiru", alternates: [], english: "to know", category: "Verbs" },
  { word: "わかる", transliteration: "wakaru", alternates: [], english: "to understand", category: "Verbs" },
  { word: "はたらく", transliteration: "hataraku", alternates: [], english: "to work", category: "Verbs" },
  { word: "よむ", transliteration: "yomu", alternates: [], english: "to read", category: "Verbs" },
  { word: "かく", transliteration: "kaku", alternates: [], english: "to write", category: "Verbs" },
  { word: "かう", transliteration: "kau", alternates: [], english: "to buy", category: "Verbs" },
  { word: "あそぶ", transliteration: "asobu", alternates: [], english: "to play", category: "Verbs" },
  { word: "うたう", transliteration: "utau", alternates: [], english: "to sing", category: "Verbs" },
  { word: "かんがえる", transliteration: "kangaeru", alternates: [], english: "to think", category: "Verbs" },
  { word: "いきる", transliteration: "ikiru", alternates: [], english: "to live", category: "Verbs" },
  { word: "はしる", transliteration: "hashiru", alternates: [], english: "to run", category: "Verbs" },

  // Adjectives
  { word: "おおきい", transliteration: "ookii", alternates: ["okii"], english: "big / large", category: "Adjectives" },
  { word: "ちいさい", transliteration: "chiisai", alternates: ["chisai"], english: "small / little", category: "Adjectives" },
  { word: "いい", transliteration: "ii", alternates: ["yoi"], english: "good / nice", category: "Adjectives" },
  { word: "わるい", transliteration: "warui", alternates: [], english: "bad", category: "Adjectives" },
  { word: "きれい", transliteration: "kirei", alternates: [], english: "beautiful / clean", category: "Adjectives" },
  { word: "はやい", transliteration: "hayai", alternates: [], english: "fast / early", category: "Adjectives" },
  { word: "おそい", transliteration: "osoi", alternates: [], english: "slow / late", category: "Adjectives" },
  { word: "あたたかい", transliteration: "atatakai", alternates: ["atatakaii"], english: "warm", category: "Adjectives" },
  { word: "さむい", transliteration: "samui", alternates: [], english: "cold (weather)", category: "Adjectives" },
  { word: "あたらしい", transliteration: "atarashii", alternates: ["atarashi"], english: "new", category: "Adjectives" },
  { word: "ふるい", transliteration: "furui", alternates: [], english: "old (thing)", category: "Adjectives" },
  { word: "たかい", transliteration: "takai", alternates: [], english: "expensive / tall / high", category: "Adjectives" },
  { word: "やすい", transliteration: "yasui", alternates: [], english: "cheap / easy", category: "Adjectives" },
  { word: "むずかしい", transliteration: "muzukashii", alternates: ["muzukashi"], english: "difficult", category: "Adjectives" },
  { word: "やさしい", transliteration: "yasashii", alternates: ["yasashi"], english: "easy / gentle / kind", category: "Adjectives" },

  // Places
  { word: "いえ", transliteration: "ie", alternates: [], english: "house / home", category: "Places" },
  { word: "がっこう", transliteration: "gakkou", alternates: ["gakko"], english: "school", category: "Places" },
  { word: "びょういん", transliteration: "byouin", alternates: ["byoin"], english: "hospital", category: "Places" },
  { word: "レストラン", transliteration: "resutoran", alternates: [], english: "restaurant", category: "Places" },
  { word: "ホテル", transliteration: "hoteru", alternates: [], english: "hotel", category: "Places" },
  { word: "くうこう", transliteration: "kuukou", alternates: ["kuko"], english: "airport", category: "Places" },
  { word: "えき", transliteration: "eki", alternates: [], english: "station", category: "Places" },
  { word: "こうえん", transliteration: "kouen", alternates: ["koen"], english: "park", category: "Places" },
  { word: "まち", transliteration: "machi", alternates: [], english: "town / city", category: "Places" },
  { word: "くに", transliteration: "kuni", alternates: [], english: "country", category: "Places" },
  { word: "うみ", transliteration: "umi", alternates: [], english: "sea / ocean", category: "Places" },
  { word: "やま", transliteration: "yama", alternates: [], english: "mountain", category: "Places" },
  { word: "かわ", transliteration: "kawa", alternates: [], english: "river", category: "Places" },

  // Animals
  { word: "いぬ", transliteration: "inu", alternates: [], english: "dog", category: "Animals" },
  { word: "ねこ", transliteration: "neko", alternates: [], english: "cat", category: "Animals" },
  { word: "うま", transliteration: "uma", alternates: [], english: "horse", category: "Animals" },
  { word: "うし", transliteration: "ushi", alternates: [], english: "cow", category: "Animals" },
  { word: "とり", transliteration: "tori", alternates: [], english: "bird", category: "Animals" },
  { word: "さかな", transliteration: "sakana", alternates: [], english: "fish", category: "Animals" },
  { word: "とら", transliteration: "tora", alternates: [], english: "tiger", category: "Animals" },
  { word: "くま", transliteration: "kuma", alternates: [], english: "bear", category: "Animals" },
  { word: "うさぎ", transliteration: "usagi", alternates: [], english: "rabbit", category: "Animals" },
  { word: "へび", transliteration: "hebi", alternates: [], english: "snake", category: "Animals" },

  // Nature
  { word: "たいよう", transliteration: "taiyou", alternates: ["taiyo"], english: "sun", category: "Nature" },
  { word: "つき", transliteration: "tsuki", alternates: [], english: "moon / month", category: "Nature" },
  { word: "ほし", transliteration: "hoshi", alternates: [], english: "star", category: "Nature" },
  { word: "そら", transliteration: "sora", alternates: [], english: "sky", category: "Nature" },
  { word: "くも", transliteration: "kumo", alternates: [], english: "cloud / spider", category: "Nature" },
  { word: "あめ", transliteration: "ame", alternates: [], english: "rain / candy", category: "Nature" },
  { word: "ゆき", transliteration: "yuki", alternates: [], english: "snow", category: "Nature" },
  { word: "かぜ", transliteration: "kaze", alternates: [], english: "wind / cold", category: "Nature" },
  { word: "き", transliteration: "ki", alternates: [], english: "tree / wood", category: "Nature" },
  { word: "はな", transliteration: "hana", alternates: [], english: "flower / nose", category: "Nature" },
  { word: "もり", transliteration: "mori", alternates: [], english: "forest", category: "Nature" },
  { word: "うみ", transliteration: "umi", alternates: [], english: "sea / ocean", category: "Nature" },

  // Countries
  { word: "にほん", transliteration: "nihon", alternates: ["nippon"], english: "Japan", category: "Countries" },
  { word: "かんこく", transliteration: "kankoku", alternates: [], english: "Korea", category: "Countries" },
  { word: "ちゅうごく", transliteration: "chuugoku", alternates: ["chugoku"], english: "China", category: "Countries" },
  { word: "アメリカ", transliteration: "Amerika", alternates: ["Amerika", "america"], english: "America", category: "Countries" },
  { word: "イギリス", transliteration: "Igirisu", alternates: ["igirisu"], english: "United Kingdom / England", category: "Countries" },
  { word: "フランス", transliteration: "Furansu", alternates: ["furansu"], english: "France", category: "Countries" },
  { word: "ドイツ", transliteration: "Doitsu", alternates: ["doitsu"], english: "Germany", category: "Countries" },
  { word: "イタリア", transliteration: "Itaria", alternates: ["itaria"], english: "Italy", category: "Countries" },
  { word: "スペイン", transliteration: "Supein", alternates: ["supein"], english: "Spain", category: "Countries" },
  { word: "ロシア", transliteration: "Roshia", alternates: ["roshia"], english: "Russia", category: "Countries" },

  // Time
  { word: "きょう", transliteration: "kyou", alternates: ["kyo"], english: "today", category: "Time" },
  { word: "きのう", transliteration: "kinou", alternates: ["kino"], english: "yesterday", category: "Time" },
  { word: "あした", transliteration: "ashita", alternates: ["asu"], english: "tomorrow", category: "Time" },
  { word: "いま", transliteration: "ima", alternates: [], english: "now", category: "Time" },
  { word: "じかん", transliteration: "jikan", alternates: [], english: "time / hour", category: "Time" },
  { word: "ふん", transliteration: "fun", alternates: [], english: "minute", category: "Time" },
  { word: "あさ", transliteration: "asa", alternates: [], english: "morning", category: "Time" },
  { word: "ひる", transliteration: "hiru", alternates: [], english: "noon / daytime", category: "Time" },
  { word: "ゆうがた", transliteration: "yuugata", alternates: ["yugata"], english: "evening", category: "Time" },
  { word: "よる", transliteration: "yoru", alternates: [], english: "night", category: "Time" },
  { word: "しゅう", transliteration: "shuu", alternates: ["shu"], english: "week", category: "Time" },
  { word: "とし", transliteration: "toshi", alternates: ["nen"], english: "year", category: "Time" },

  // Everyday
  { word: "ひと", transliteration: "hito", alternates: [], english: "person / people", category: "Everyday" },
  { word: "いのち", transliteration: "inochi", alternates: [], english: "life", category: "Everyday" },
  { word: "かね", transliteration: "kane", alternates: [], english: "money / metal / bell", category: "Everyday" },
  { word: "でんわ", transliteration: "denwa", alternates: [], english: "telephone", category: "Everyday" },
  { word: "パソコン", transliteration: "pasokon", alternates: [], english: "personal computer", category: "Everyday" },
  { word: "くるま", transliteration: "kuruma", alternates: [], english: "car", category: "Everyday" },
  { word: "ほん", transliteration: "hon", alternates: [], english: "book", category: "Everyday" },
  { word: "ことば", transliteration: "kotoba", alternates: [], english: "word / language", category: "Everyday" },
  { word: "しつもん", transliteration: "shitsumon", alternates: [], english: "question", category: "Everyday" },
  { word: "ともだち", transliteration: "tomodachi", alternates: [], english: "friend", category: "Everyday" },
  { word: "あい", transliteration: "ai", alternates: [], english: "love", category: "Everyday" },
  { word: "しあわせ", transliteration: "shiawase", alternates: [], english: "happiness", category: "Everyday" },
  { word: "しんじつ", transliteration: "shinjitsu", alternates: [], english: "truth", category: "Everyday" },
  { word: "じゆう", transliteration: "jiyuu", alternates: ["jiyu"], english: "freedom", category: "Everyday" },
  { word: "へいわ", transliteration: "heiwa", alternates: [], english: "peace", category: "Everyday" },
];
