'use strict';

const ALPHABET_REF_KO = [
  // Consonants
  ['ㄱ', 'g/k'],  ['ㄴ', 'n'],   ['ㄷ', 'd/t'],  ['ㄹ', 'r/l'],
  ['ㅁ', 'm'],    ['ㅂ', 'b/p'], ['ㅅ', 's'],    ['ㅇ', 'ng'],
  ['ㅈ', 'j'],    ['ㅊ', 'ch'],  ['ㅋ', 'k'],    ['ㅌ', 't'],
  ['ㅍ', 'p'],    ['ㅎ', 'h'],
  // Vowels
  ['ㅏ', 'a'],    ['ㅑ', 'ya'],  ['ㅓ', 'eo'],   ['ㅕ', 'yeo'],
  ['ㅗ', 'o'],    ['ㅛ', 'yo'],  ['ㅜ', 'u'],    ['ㅠ', 'yu'],
  ['ㅡ', 'eu'],   ['ㅣ', 'i'],   ['ㅐ', 'ae'],   ['ㅔ', 'e'],
];

const WORDS_KO = [
  // Greetings
  { word: "안녕하세요", transliteration: "annyeonghaseyo", alternates: [], english: "hello (formal)", category: "Greetings" },
  { word: "안녕", transliteration: "annyeong", alternates: [], english: "hi / bye (informal)", category: "Greetings" },
  { word: "감사합니다", transliteration: "gamsahamnida", alternates: [], english: "thank you (formal)", category: "Greetings" },
  { word: "고마워요", transliteration: "gomawoyo", alternates: ["gomawo"], english: "thank you (informal)", category: "Greetings" },
  { word: "네", transliteration: "ne", alternates: ["ye"], english: "yes", category: "Greetings" },
  { word: "아니요", transliteration: "aniyo", alternates: ["anio"], english: "no", category: "Greetings" },
  { word: "죄송합니다", transliteration: "joesonghamnida", alternates: [], english: "I'm sorry (formal)", category: "Greetings" },
  { word: "괜찮아요", transliteration: "gwaenchanayo", alternates: ["gwenchanayo"], english: "it's okay / are you okay?", category: "Greetings" },
  { word: "안녕히 가세요", transliteration: "annyeonghi gaseyo", alternates: [], english: "goodbye (to one leaving)", category: "Greetings" },
  { word: "안녕히 계세요", transliteration: "annyeonghi gyeseyo", alternates: [], english: "goodbye (to one staying)", category: "Greetings" },
  { word: "반갑습니다", transliteration: "bangapseumnida", alternates: ["bangapseubnida"], english: "nice to meet you", category: "Greetings" },

  // Numbers
  { word: "일", transliteration: "il", alternates: [], english: "one (Sino-Korean)", category: "Numbers" },
  { word: "이", transliteration: "i", alternates: [], english: "two (Sino-Korean)", category: "Numbers" },
  { word: "삼", transliteration: "sam", alternates: [], english: "three (Sino-Korean)", category: "Numbers" },
  { word: "사", transliteration: "sa", alternates: [], english: "four (Sino-Korean)", category: "Numbers" },
  { word: "오", transliteration: "o", alternates: [], english: "five (Sino-Korean)", category: "Numbers" },
  { word: "육", transliteration: "yuk", alternates: ["ryuk"], english: "six (Sino-Korean)", category: "Numbers" },
  { word: "칠", transliteration: "chil", alternates: [], english: "seven (Sino-Korean)", category: "Numbers" },
  { word: "팔", transliteration: "pal", alternates: [], english: "eight (Sino-Korean)", category: "Numbers" },
  { word: "구", transliteration: "gu", alternates: [], english: "nine (Sino-Korean)", category: "Numbers" },
  { word: "십", transliteration: "sip", alternates: [], english: "ten (Sino-Korean)", category: "Numbers" },
  { word: "백", transliteration: "baek", alternates: [], english: "one hundred", category: "Numbers" },
  { word: "천", transliteration: "cheon", alternates: [], english: "one thousand", category: "Numbers" },

  // Days
  { word: "월요일", transliteration: "woryoil", alternates: ["wollyoil"], english: "Monday", category: "Days" },
  { word: "화요일", transliteration: "hwayoil", alternates: [], english: "Tuesday", category: "Days" },
  { word: "수요일", transliteration: "suyoil", alternates: [], english: "Wednesday", category: "Days" },
  { word: "목요일", transliteration: "mogyoil", alternates: [], english: "Thursday", category: "Days" },
  { word: "금요일", transliteration: "geumyoil", alternates: [], english: "Friday", category: "Days" },
  { word: "토요일", transliteration: "toyoil", alternates: [], english: "Saturday", category: "Days" },
  { word: "일요일", transliteration: "iryoil", alternates: ["illyoil"], english: "Sunday", category: "Days" },

  // Months
  { word: "일월", transliteration: "irwol", alternates: ["ilwol"], english: "January", category: "Months" },
  { word: "이월", transliteration: "iwol", alternates: [], english: "February", category: "Months" },
  { word: "삼월", transliteration: "samwol", alternates: [], english: "March", category: "Months" },
  { word: "사월", transliteration: "sawol", alternates: [], english: "April", category: "Months" },
  { word: "오월", transliteration: "owol", alternates: [], english: "May", category: "Months" },
  { word: "유월", transliteration: "yuwol", alternates: [], english: "June", category: "Months" },
  { word: "칠월", transliteration: "chirwol", alternates: ["chilwol"], english: "July", category: "Months" },
  { word: "팔월", transliteration: "parwol", alternates: ["palwol"], english: "August", category: "Months" },
  { word: "구월", transliteration: "guwol", alternates: [], english: "September", category: "Months" },
  { word: "시월", transliteration: "siwol", alternates: [], english: "October", category: "Months" },
  { word: "십일월", transliteration: "sibirwol", alternates: ["sibilwol"], english: "November", category: "Months" },
  { word: "십이월", transliteration: "sibiwol", alternates: [], english: "December", category: "Months" },

  // Family
  { word: "어머니", transliteration: "eomeoni", alternates: [], english: "mother", category: "Family" },
  { word: "아버지", transliteration: "abeoji", alternates: [], english: "father", category: "Family" },
  { word: "엄마", transliteration: "eomma", alternates: [], english: "mom (informal)", category: "Family" },
  { word: "아빠", transliteration: "appa", alternates: [], english: "dad (informal)", category: "Family" },
  { word: "오빠", transliteration: "oppa", alternates: [], english: "older brother (female speaker)", category: "Family" },
  { word: "언니", transliteration: "eonni", alternates: [], english: "older sister (female speaker)", category: "Family" },
  { word: "형", transliteration: "hyeong", alternates: [], english: "older brother (male speaker)", category: "Family" },
  { word: "누나", transliteration: "nuna", alternates: [], english: "older sister (male speaker)", category: "Family" },
  { word: "동생", transliteration: "dongsaeng", alternates: [], english: "younger sibling", category: "Family" },
  { word: "아들", transliteration: "adeul", alternates: [], english: "son", category: "Family" },
  { word: "딸", transliteration: "ttal", alternates: [], english: "daughter", category: "Family" },
  { word: "할아버지", transliteration: "harabeoji", alternates: [], english: "grandfather", category: "Family" },
  { word: "할머니", transliteration: "halmeoni", alternates: [], english: "grandmother", category: "Family" },

  // Colors
  { word: "빨간색", transliteration: "ppalganssaek", alternates: ["ppalgansaek"], english: "red", category: "Colors" },
  { word: "파란색", transliteration: "paranssaek", alternates: ["paransaek"], english: "blue", category: "Colors" },
  { word: "초록색", transliteration: "choroksaek", alternates: ["choroksaek"], english: "green", category: "Colors" },
  { word: "노란색", transliteration: "noransaek", alternates: ["noranssaek"], english: "yellow", category: "Colors" },
  { word: "하얀색", transliteration: "hayansaek", alternates: ["hayanssaek"], english: "white", category: "Colors" },
  { word: "검은색", transliteration: "geomeunsaek", alternates: [], english: "black", category: "Colors" },
  { word: "주황색", transliteration: "juhwangsaek", alternates: [], english: "orange", category: "Colors" },
  { word: "보라색", transliteration: "borasaek", alternates: ["borassaek"], english: "purple", category: "Colors" },
  { word: "분홍색", transliteration: "bunhongsaek", alternates: [], english: "pink", category: "Colors" },
  { word: "갈색", transliteration: "galssaek", alternates: ["galsaek"], english: "brown", category: "Colors" },
  { word: "회색", transliteration: "hoessaek", alternates: ["hoesaek"], english: "gray", category: "Colors" },

  // Food & Drink
  { word: "밥", transliteration: "bap", alternates: [], english: "cooked rice / meal", category: "Food & Drink" },
  { word: "물", transliteration: "mul", alternates: [], english: "water", category: "Food & Drink" },
  { word: "우유", transliteration: "uyu", alternates: [], english: "milk", category: "Food & Drink" },
  { word: "고기", transliteration: "gogi", alternates: [], english: "meat", category: "Food & Drink" },
  { word: "생선", transliteration: "saengseon", alternates: [], english: "fish", category: "Food & Drink" },
  { word: "달걀", transliteration: "dalgyal", alternates: ["dalgal"], english: "egg", category: "Food & Drink" },
  { word: "커피", transliteration: "keopi", alternates: ["keoppi"], english: "coffee", category: "Food & Drink" },
  { word: "차", transliteration: "cha", alternates: [], english: "tea", category: "Food & Drink" },
  { word: "맥주", transliteration: "maekju", alternates: [], english: "beer", category: "Food & Drink" },
  { word: "소주", transliteration: "soju", alternates: ["sochu"], english: "soju (Korean rice wine)", category: "Food & Drink" },
  { word: "김치", transliteration: "gimchi", alternates: ["kimchi"], english: "kimchi", category: "Food & Drink" },
  { word: "불고기", transliteration: "bulgogi", alternates: [], english: "bulgogi (marinated beef)", category: "Food & Drink" },
  { word: "떡볶이", transliteration: "tteokbokki", alternates: ["ddukbokki"], english: "spicy rice cakes", category: "Food & Drink" },
  { word: "빵", transliteration: "ppang", alternates: ["pang"], english: "bread", category: "Food & Drink" },
  { word: "치즈", transliteration: "chijeu", alternates: [], english: "cheese", category: "Food & Drink" },
  { word: "국", transliteration: "guk", alternates: [], english: "soup", category: "Food & Drink" },
  { word: "라면", transliteration: "ramyeon", alternates: ["ramen"], english: "ramen noodles", category: "Food & Drink" },
  { word: "사과", transliteration: "sagwa", alternates: [], english: "apple", category: "Food & Drink" },
  { word: "바나나", transliteration: "banana", alternates: [], english: "banana", category: "Food & Drink" },
  { word: "설탕", transliteration: "seoltang", alternates: [], english: "sugar", category: "Food & Drink" },
  { word: "소금", transliteration: "sogeum", alternates: [], english: "salt", category: "Food & Drink" },

  // Body
  { word: "머리", transliteration: "meori", alternates: [], english: "head / hair", category: "Body" },
  { word: "얼굴", transliteration: "eolgul", alternates: [], english: "face", category: "Body" },
  { word: "눈", transliteration: "nun", alternates: [], english: "eye / snow", category: "Body" },
  { word: "귀", transliteration: "gwi", alternates: [], english: "ear", category: "Body" },
  { word: "코", transliteration: "ko", alternates: [], english: "nose", category: "Body" },
  { word: "입", transliteration: "ip", alternates: [], english: "mouth", category: "Body" },
  { word: "손", transliteration: "son", alternates: [], english: "hand", category: "Body" },
  { word: "발", transliteration: "bal", alternates: [], english: "foot", category: "Body" },
  { word: "심장", transliteration: "simjang", alternates: [], english: "heart", category: "Body" },
  { word: "등", transliteration: "deung", alternates: [], english: "back", category: "Body" },
  { word: "이", transliteration: "i", alternates: [], english: "tooth", category: "Body" },
  { word: "다리", transliteration: "dari", alternates: [], english: "leg", category: "Body" },

  // Verbs
  { word: "먹다", transliteration: "meokda", alternates: [], english: "to eat", category: "Verbs" },
  { word: "마시다", transliteration: "masida", alternates: [], english: "to drink", category: "Verbs" },
  { word: "자다", transliteration: "jada", alternates: [], english: "to sleep", category: "Verbs" },
  { word: "걷다", transliteration: "geotda", alternates: ["geodda"], english: "to walk", category: "Verbs" },
  { word: "말하다", transliteration: "malhada", alternates: [], english: "to speak", category: "Verbs" },
  { word: "보다", transliteration: "boda", alternates: [], english: "to see / watch", category: "Verbs" },
  { word: "듣다", transliteration: "deutda", alternates: ["deudda"], english: "to hear / listen", category: "Verbs" },
  { word: "사랑하다", transliteration: "saranghada", alternates: [], english: "to love", category: "Verbs" },
  { word: "원하다", transliteration: "wonhada", alternates: [], english: "to want", category: "Verbs" },
  { word: "가다", transliteration: "gada", alternates: [], english: "to go", category: "Verbs" },
  { word: "오다", transliteration: "oda", alternates: [], english: "to come", category: "Verbs" },
  { word: "알다", transliteration: "alda", alternates: [], english: "to know", category: "Verbs" },
  { word: "이해하다", transliteration: "ihaehada", alternates: [], english: "to understand", category: "Verbs" },
  { word: "일하다", transliteration: "ilhada", alternates: [], english: "to work", category: "Verbs" },
  { word: "읽다", transliteration: "ikda", alternates: ["ilgda"], english: "to read", category: "Verbs" },
  { word: "쓰다", transliteration: "sseuda", alternates: ["sseuda"], english: "to write", category: "Verbs" },
  { word: "사다", transliteration: "sada", alternates: [], english: "to buy", category: "Verbs" },
  { word: "놀다", transliteration: "nolda", alternates: [], english: "to play", category: "Verbs" },
  { word: "노래하다", transliteration: "noraehada", alternates: [], english: "to sing", category: "Verbs" },
  { word: "생각하다", transliteration: "saenggakada", alternates: ["saenggakhada"], english: "to think", category: "Verbs" },
  { word: "살다", transliteration: "salda", alternates: [], english: "to live", category: "Verbs" },

  // Adjectives
  { word: "크다", transliteration: "keuda", alternates: [], english: "to be big", category: "Adjectives" },
  { word: "작다", transliteration: "jakda", alternates: [], english: "to be small", category: "Adjectives" },
  { word: "좋다", transliteration: "jota", alternates: ["jokda"], english: "to be good", category: "Adjectives" },
  { word: "나쁘다", transliteration: "nappeuda", alternates: [], english: "to be bad", category: "Adjectives" },
  { word: "예쁘다", transliteration: "yeppeuda", alternates: [], english: "to be pretty", category: "Adjectives" },
  { word: "빠르다", transliteration: "ppareuda", alternates: ["bareuda"], english: "to be fast", category: "Adjectives" },
  { word: "느리다", transliteration: "neurida", alternates: [], english: "to be slow", category: "Adjectives" },
  { word: "따뜻하다", transliteration: "ttatteutada", alternates: ["dtatdeutada"], english: "to be warm", category: "Adjectives" },
  { word: "춥다", transliteration: "chupda", alternates: [], english: "to be cold", category: "Adjectives" },
  { word: "새롭다", transliteration: "saeropda", alternates: [], english: "to be new", category: "Adjectives" },
  { word: "비싸다", transliteration: "bissada", alternates: [], english: "to be expensive", category: "Adjectives" },
  { word: "싸다", transliteration: "ssada", alternates: [], english: "to be cheap", category: "Adjectives" },
  { word: "어렵다", transliteration: "eoryeopda", alternates: [], english: "to be difficult", category: "Adjectives" },
  { word: "쉽다", transliteration: "swipda", alternates: ["swida"], english: "to be easy", category: "Adjectives" },
  { word: "재미있다", transliteration: "jaemiitda", alternates: ["jaemiissda"], english: "to be fun / interesting", category: "Adjectives" },

  // Places
  { word: "집", transliteration: "jip", alternates: [], english: "house / home", category: "Places" },
  { word: "학교", transliteration: "hakgyo", alternates: [], english: "school", category: "Places" },
  { word: "병원", transliteration: "byeongwon", alternates: [], english: "hospital", category: "Places" },
  { word: "식당", transliteration: "sikdang", alternates: [], english: "restaurant", category: "Places" },
  { word: "호텔", transliteration: "hotel", alternates: ["hottel"], english: "hotel", category: "Places" },
  { word: "공항", transliteration: "gonghang", alternates: [], english: "airport", category: "Places" },
  { word: "역", transliteration: "yeok", alternates: [], english: "station", category: "Places" },
  { word: "공원", transliteration: "gongwon", alternates: [], english: "park", category: "Places" },
  { word: "도시", transliteration: "dosi", alternates: [], english: "city", category: "Places" },
  { word: "나라", transliteration: "nara", alternates: [], english: "country", category: "Places" },
  { word: "바다", transliteration: "bada", alternates: [], english: "sea / ocean", category: "Places" },
  { word: "산", transliteration: "san", alternates: [], english: "mountain", category: "Places" },
  { word: "강", transliteration: "gang", alternates: [], english: "river", category: "Places" },

  // Animals
  { word: "개", transliteration: "gae", alternates: [], english: "dog", category: "Animals" },
  { word: "고양이", transliteration: "goyangi", alternates: [], english: "cat", category: "Animals" },
  { word: "말", transliteration: "mal", alternates: [], english: "horse", category: "Animals" },
  { word: "소", transliteration: "so", alternates: [], english: "cow", category: "Animals" },
  { word: "새", transliteration: "sae", alternates: [], english: "bird", category: "Animals" },
  { word: "물고기", transliteration: "mulgogi", alternates: [], english: "fish", category: "Animals" },
  { word: "호랑이", transliteration: "horangi", alternates: [], english: "tiger", category: "Animals" },
  { word: "곰", transliteration: "gom", alternates: [], english: "bear", category: "Animals" },
  { word: "돼지", transliteration: "dwaeji", alternates: [], english: "pig", category: "Animals" },
  { word: "토끼", transliteration: "tokki", alternates: [], english: "rabbit", category: "Animals" },

  // Nature
  { word: "태양", transliteration: "taeyang", alternates: [], english: "sun", category: "Nature" },
  { word: "달", transliteration: "dal", alternates: [], english: "moon", category: "Nature" },
  { word: "별", transliteration: "byeol", alternates: [], english: "star", category: "Nature" },
  { word: "하늘", transliteration: "haneul", alternates: [], english: "sky", category: "Nature" },
  { word: "구름", transliteration: "gureum", alternates: [], english: "cloud", category: "Nature" },
  { word: "비", transliteration: "bi", alternates: [], english: "rain", category: "Nature" },
  { word: "눈", transliteration: "nun", alternates: [], english: "snow / eye", category: "Nature" },
  { word: "바람", transliteration: "baram", alternates: [], english: "wind", category: "Nature" },
  { word: "나무", transliteration: "namu", alternates: [], english: "tree", category: "Nature" },
  { word: "꽃", transliteration: "kkot", alternates: ["kot"], english: "flower", category: "Nature" },
  { word: "숲", transliteration: "sup", alternates: [], english: "forest", category: "Nature" },
  { word: "강", transliteration: "gang", alternates: [], english: "river", category: "Nature" },

  // Countries
  { word: "한국", transliteration: "hanguk", alternates: ["hankuk"], english: "Korea", category: "Countries" },
  { word: "일본", transliteration: "ilbon", alternates: [], english: "Japan", category: "Countries" },
  { word: "중국", transliteration: "jungguk", alternates: [], english: "China", category: "Countries" },
  { word: "미국", transliteration: "miguk", alternates: [], english: "United States / America", category: "Countries" },
  { word: "영국", transliteration: "yeongguk", alternates: [], english: "United Kingdom / England", category: "Countries" },
  { word: "프랑스", transliteration: "peurangseu", alternates: [], english: "France", category: "Countries" },
  { word: "독일", transliteration: "dogil", alternates: [], english: "Germany", category: "Countries" },
  { word: "이탈리아", transliteration: "itallia", alternates: ["itallia"], english: "Italy", category: "Countries" },
  { word: "스페인", transliteration: "seupein", alternates: [], english: "Spain", category: "Countries" },
  { word: "러시아", transliteration: "reosia", alternates: [], english: "Russia", category: "Countries" },

  // Time
  { word: "오늘", transliteration: "oneul", alternates: [], english: "today", category: "Time" },
  { word: "어제", transliteration: "eoje", alternates: [], english: "yesterday", category: "Time" },
  { word: "내일", transliteration: "naeil", alternates: [], english: "tomorrow", category: "Time" },
  { word: "지금", transliteration: "jigeum", alternates: [], english: "now", category: "Time" },
  { word: "시간", transliteration: "sigan", alternates: [], english: "hour / time", category: "Time" },
  { word: "분", transliteration: "bun", alternates: [], english: "minute", category: "Time" },
  { word: "아침", transliteration: "achim", alternates: [], english: "morning / breakfast", category: "Time" },
  { word: "점심", transliteration: "jeomsim", alternates: [], english: "noon / lunch", category: "Time" },
  { word: "저녁", transliteration: "jeonyeok", alternates: [], english: "evening / dinner", category: "Time" },
  { word: "밤", transliteration: "bam", alternates: [], english: "night", category: "Time" },
  { word: "주", transliteration: "ju", alternates: [], english: "week", category: "Time" },
  { word: "월", transliteration: "wol", alternates: [], english: "month", category: "Time" },
  { word: "년", transliteration: "nyeon", alternates: ["yeon"], english: "year", category: "Time" },

  // Everyday
  { word: "사람", transliteration: "saram", alternates: [], english: "person", category: "Everyday" },
  { word: "돈", transliteration: "don", alternates: [], english: "money", category: "Everyday" },
  { word: "전화", transliteration: "jeonhwa", alternates: [], english: "telephone / call", category: "Everyday" },
  { word: "컴퓨터", transliteration: "keompyuteo", alternates: ["keompyuteo"], english: "computer", category: "Everyday" },
  { word: "자동차", transliteration: "jadongcha", alternates: [], english: "car", category: "Everyday" },
  { word: "책", transliteration: "chaek", alternates: [], english: "book", category: "Everyday" },
  { word: "단어", transliteration: "daneo", alternates: [], english: "word / vocabulary", category: "Everyday" },
  { word: "언어", transliteration: "eoneo", alternates: [], english: "language", category: "Everyday" },
  { word: "질문", transliteration: "jilmun", alternates: [], english: "question", category: "Everyday" },
  { word: "친구", transliteration: "chingu", alternates: [], english: "friend", category: "Everyday" },
  { word: "사랑", transliteration: "sarang", alternates: [], english: "love", category: "Everyday" },
  { word: "행복", transliteration: "haengbok", alternates: [], english: "happiness", category: "Everyday" },
  { word: "진실", transliteration: "jinsil", alternates: [], english: "truth", category: "Everyday" },
  { word: "자유", transliteration: "jayu", alternates: [], english: "freedom", category: "Everyday" },
  { word: "평화", transliteration: "pyeonghwa", alternates: [], english: "peace", category: "Everyday" },
];
