'use strict';

const ALPHABET_REF_EL = [
  ['Α α', 'a'],    ['Β β', 'v'],    ['Γ γ', 'g'],    ['Δ δ', 'd'],
  ['Ε ε', 'e'],    ['Ζ ζ', 'z'],    ['Η η', 'i'],    ['Θ θ', 'th'],
  ['Ι ι', 'i'],    ['Κ κ', 'k'],    ['Λ λ', 'l'],    ['Μ μ', 'm'],
  ['Ν ν', 'n'],    ['Ξ ξ', 'x'],    ['Ο ο', 'o'],    ['Π π', 'p'],
  ['Ρ ρ', 'r'],    ['Σ σ/ς', 's'],  ['Τ τ', 't'],    ['Υ υ', 'y/i'],
  ['Φ φ', 'f'],    ['Χ χ', 'ch'],   ['Ψ ψ', 'ps'],   ['Ω ω', 'o'],
];

const WORDS_EL = [
  // Greetings
  { word: "γεια", transliteration: "geia", alternates: ["yeia", "ya"], english: "hi / hello (informal)", category: "Greetings" },
  { word: "γεια σου", transliteration: "geia sou", alternates: ["yeia sou", "ya sou"], english: "hello (to one person)", category: "Greetings" },
  { word: "γεια σας", transliteration: "geia sas", alternates: ["yeia sas"], english: "hello (formal / plural)", category: "Greetings" },
  { word: "καλημέρα", transliteration: "kalimera", alternates: [], english: "good morning", category: "Greetings" },
  { word: "καλησπέρα", transliteration: "kalispera", alternates: [], english: "good evening", category: "Greetings" },
  { word: "καληνύχτα", transliteration: "kalinychta", alternates: ["kalinihta"], english: "good night", category: "Greetings" },
  { word: "αντίο", transliteration: "antio", alternates: [], english: "goodbye", category: "Greetings" },
  { word: "παρακαλώ", transliteration: "parakalo", alternates: [], english: "please / you're welcome", category: "Greetings" },
  { word: "ευχαριστώ", transliteration: "efcharisto", alternates: ["evcharisto", "efharistw"], english: "thank you", category: "Greetings" },
  { word: "συγγνώμη", transliteration: "signomi", alternates: ["singnomi"], english: "sorry / excuse me", category: "Greetings" },
  { word: "ναι", transliteration: "nai", alternates: [], english: "yes", category: "Greetings" },
  { word: "όχι", transliteration: "ochi", alternates: [], english: "no", category: "Greetings" },

  // Numbers
  { word: "ένα", transliteration: "ena", alternates: [], english: "one", category: "Numbers" },
  { word: "δύο", transliteration: "dyo", alternates: ["dio"], english: "two", category: "Numbers" },
  { word: "τρία", transliteration: "tria", alternates: [], english: "three", category: "Numbers" },
  { word: "τέσσερα", transliteration: "tessera", alternates: [], english: "four", category: "Numbers" },
  { word: "πέντε", transliteration: "pente", alternates: [], english: "five", category: "Numbers" },
  { word: "έξι", transliteration: "exi", alternates: ["ehi"], english: "six", category: "Numbers" },
  { word: "επτά", transliteration: "epta", alternates: ["efta"], english: "seven", category: "Numbers" },
  { word: "οκτώ", transliteration: "okto", alternates: ["ochto"], english: "eight", category: "Numbers" },
  { word: "εννέα", transliteration: "ennea", alternates: ["ennia", "enia"], english: "nine", category: "Numbers" },
  { word: "δέκα", transliteration: "deka", alternates: [], english: "ten", category: "Numbers" },
  { word: "είκοσι", transliteration: "eikosi", alternates: ["ikosi"], english: "twenty", category: "Numbers" },
  { word: "εκατό", transliteration: "ekato", alternates: [], english: "one hundred", category: "Numbers" },
  { word: "χίλια", transliteration: "chilia", alternates: ["hilia"], english: "one thousand", category: "Numbers" },

  // Days
  { word: "Δευτέρα", transliteration: "Deftera", alternates: ["deftera"], english: "Monday", category: "Days" },
  { word: "Τρίτη", transliteration: "Triti", alternates: ["triti"], english: "Tuesday", category: "Days" },
  { word: "Τετάρτη", transliteration: "Tetarti", alternates: ["tetarti"], english: "Wednesday", category: "Days" },
  { word: "Πέμπτη", transliteration: "Pempti", alternates: ["pempti"], english: "Thursday", category: "Days" },
  { word: "Παρασκευή", transliteration: "Paraskevi", alternates: ["paraskevi"], english: "Friday", category: "Days" },
  { word: "Σάββατο", transliteration: "Savvato", alternates: ["savato"], english: "Saturday", category: "Days" },
  { word: "Κυριακή", transliteration: "Kyriaki", alternates: ["kyriaki", "Kiriaki"], english: "Sunday", category: "Days" },

  // Months
  { word: "Ιανουάριος", transliteration: "Ianouarios", alternates: ["ianouarios", "Ianouarios"], english: "January", category: "Months" },
  { word: "Φεβρουάριος", transliteration: "Fevrouarios", alternates: ["fevrouarios"], english: "February", category: "Months" },
  { word: "Μάρτιος", transliteration: "Martios", alternates: ["martios"], english: "March", category: "Months" },
  { word: "Απρίλιος", transliteration: "Aprilios", alternates: ["aprilios"], english: "April", category: "Months" },
  { word: "Μάιος", transliteration: "Maios", alternates: ["maios"], english: "May", category: "Months" },
  { word: "Ιούνιος", transliteration: "Iounios", alternates: ["iounios"], english: "June", category: "Months" },
  { word: "Ιούλιος", transliteration: "Ioulios", alternates: ["ioulios"], english: "July", category: "Months" },
  { word: "Αύγουστος", transliteration: "Avgoustos", alternates: ["avgoustos", "Afkoustos"], english: "August", category: "Months" },
  { word: "Σεπτέμβριος", transliteration: "Septemvrios", alternates: ["septemvrios"], english: "September", category: "Months" },
  { word: "Οκτώβριος", transliteration: "Oktovrios", alternates: ["oktovrios"], english: "October", category: "Months" },
  { word: "Νοέμβριος", transliteration: "Noemvrios", alternates: ["noemvrios"], english: "November", category: "Months" },
  { word: "Δεκέμβριος", transliteration: "Dekemvrios", alternates: ["dekemvrios"], english: "December", category: "Months" },

  // Family
  { word: "μητέρα", transliteration: "mitera", alternates: [], english: "mother", category: "Family" },
  { word: "πατέρας", transliteration: "pateras", alternates: [], english: "father", category: "Family" },
  { word: "αδερφός", transliteration: "aderfos", alternates: ["adelfos"], english: "brother", category: "Family" },
  { word: "αδερφή", transliteration: "aderfi", alternates: ["adelfi"], english: "sister", category: "Family" },
  { word: "γιος", transliteration: "gios", alternates: ["yios"], english: "son", category: "Family" },
  { word: "κόρη", transliteration: "kori", alternates: [], english: "daughter", category: "Family" },
  { word: "παππούς", transliteration: "papous", alternates: [], english: "grandfather", category: "Family" },
  { word: "γιαγιά", transliteration: "yiayia", alternates: ["giagia", "yiayia"], english: "grandmother", category: "Family" },
  { word: "θείος", transliteration: "theios", alternates: ["thios"], english: "uncle", category: "Family" },
  { word: "θεία", transliteration: "theia", alternates: ["thia"], english: "aunt", category: "Family" },
  { word: "σύζυγος", transliteration: "syzygos", alternates: ["sizygos"], english: "spouse", category: "Family" },
  { word: "παιδί", transliteration: "peidi", alternates: ["paidi"], english: "child", category: "Family" },

  // Colors
  { word: "κόκκινο", transliteration: "kokkino", alternates: [], english: "red", category: "Colors" },
  { word: "μπλε", transliteration: "ble", alternates: [], english: "blue", category: "Colors" },
  { word: "πράσινο", transliteration: "prasino", alternates: [], english: "green", category: "Colors" },
  { word: "κίτρινο", transliteration: "kitrino", alternates: [], english: "yellow", category: "Colors" },
  { word: "μαύρο", transliteration: "mavro", alternates: [], english: "black", category: "Colors" },
  { word: "άσπρο", transliteration: "aspro", alternates: ["lefko"], english: "white", category: "Colors" },
  { word: "πορτοκαλί", transliteration: "portokali", alternates: [], english: "orange", category: "Colors" },
  { word: "ροζ", transliteration: "roz", alternates: [], english: "pink", category: "Colors" },
  { word: "μωβ", transliteration: "mov", alternates: [], english: "purple", category: "Colors" },
  { word: "καφέ", transliteration: "kafe", alternates: [], english: "brown", category: "Colors" },
  { word: "γκρι", transliteration: "gri", alternates: [], english: "gray", category: "Colors" },

  // Food & Drink
  { word: "ψωμί", transliteration: "psomi", alternates: [], english: "bread", category: "Food & Drink" },
  { word: "νερό", transliteration: "nero", alternates: [], english: "water", category: "Food & Drink" },
  { word: "γάλα", transliteration: "gala", alternates: [], english: "milk", category: "Food & Drink" },
  { word: "κρέας", transliteration: "kreas", alternates: [], english: "meat", category: "Food & Drink" },
  { word: "ψάρι", transliteration: "psari", alternates: [], english: "fish", category: "Food & Drink" },
  { word: "τυρί", transliteration: "tyri", alternates: [], english: "cheese", category: "Food & Drink" },
  { word: "αυγό", transliteration: "avgo", alternates: [], english: "egg", category: "Food & Drink" },
  { word: "καφές", transliteration: "kafes", alternates: [], english: "coffee", category: "Food & Drink" },
  { word: "τσάι", transliteration: "tsai", alternates: [], english: "tea", category: "Food & Drink" },
  { word: "κρασί", transliteration: "krasi", alternates: [], english: "wine", category: "Food & Drink" },
  { word: "μπύρα", transliteration: "bira", alternates: [], english: "beer", category: "Food & Drink" },
  { word: "ελιά", transliteration: "elia", alternates: [], english: "olive", category: "Food & Drink" },
  { word: "ντομάτα", transliteration: "domata", alternates: ["ntomata"], english: "tomato", category: "Food & Drink" },
  { word: "πατάτα", transliteration: "patata", alternates: [], english: "potato", category: "Food & Drink" },
  { word: "σαλάτα", transliteration: "salata", alternates: [], english: "salad", category: "Food & Drink" },
  { word: "σούπα", transliteration: "soupa", alternates: ["supa"], english: "soup", category: "Food & Drink" },
  { word: "ρύζι", transliteration: "ryzi", alternates: ["rizi"], english: "rice", category: "Food & Drink" },
  { word: "κοτόπουλο", transliteration: "kotopoulo", alternates: [], english: "chicken", category: "Food & Drink" },
  { word: "λεμόνι", transliteration: "lemoni", alternates: [], english: "lemon", category: "Food & Drink" },
  { word: "σκόρδο", transliteration: "skordo", alternates: [], english: "garlic", category: "Food & Drink" },
  { word: "μέλι", transliteration: "meli", alternates: [], english: "honey", category: "Food & Drink" },
  { word: "ζάχαρη", transliteration: "zachari", alternates: ["zahary"], english: "sugar", category: "Food & Drink" },
  { word: "αλάτι", transliteration: "alati", alternates: [], english: "salt", category: "Food & Drink" },

  // Body
  { word: "κεφάλι", transliteration: "kefali", alternates: [], english: "head", category: "Body" },
  { word: "πρόσωπο", transliteration: "prosopo", alternates: [], english: "face", category: "Body" },
  { word: "μάτι", transliteration: "mati", alternates: [], english: "eye", category: "Body" },
  { word: "αυτί", transliteration: "afti", alternates: ["avti"], english: "ear", category: "Body" },
  { word: "μύτη", transliteration: "myti", alternates: ["miti"], english: "nose", category: "Body" },
  { word: "στόμα", transliteration: "stoma", alternates: [], english: "mouth", category: "Body" },
  { word: "χέρι", transliteration: "cheri", alternates: ["heri"], english: "hand / arm", category: "Body" },
  { word: "πόδι", transliteration: "podi", alternates: [], english: "leg / foot", category: "Body" },
  { word: "καρδιά", transliteration: "kardia", alternates: [], english: "heart", category: "Body" },
  { word: "ράχη", transliteration: "rachi", alternates: ["rahi"], english: "back", category: "Body" },
  { word: "δόντι", transliteration: "donti", alternates: [], english: "tooth", category: "Body" },
  { word: "μαλλιά", transliteration: "mallia", alternates: [], english: "hair", category: "Body" },

  // Verbs
  { word: "τρώω", transliteration: "troo", alternates: ["trowo"], english: "to eat", category: "Verbs" },
  { word: "πίνω", transliteration: "pino", alternates: [], english: "to drink", category: "Verbs" },
  { word: "κοιμάμαι", transliteration: "koimamai", alternates: ["kimamai"], english: "to sleep", category: "Verbs" },
  { word: "περπατώ", transliteration: "perpato", alternates: [], english: "to walk", category: "Verbs" },
  { word: "μιλώ", transliteration: "milo", alternates: [], english: "to speak / to talk", category: "Verbs" },
  { word: "βλέπω", transliteration: "vlepo", alternates: [], english: "to see / to watch", category: "Verbs" },
  { word: "ακούω", transliteration: "akouo", alternates: ["akuo"], english: "to hear / to listen", category: "Verbs" },
  { word: "αγαπώ", transliteration: "agapo", alternates: [], english: "to love", category: "Verbs" },
  { word: "θέλω", transliteration: "thelo", alternates: [], english: "to want", category: "Verbs" },
  { word: "πηγαίνω", transliteration: "pigaino", alternates: ["pijaino"], english: "to go", category: "Verbs" },
  { word: "έρχομαι", transliteration: "erchomai", alternates: ["erhomai"], english: "to come", category: "Verbs" },
  { word: "ξέρω", transliteration: "xero", alternates: ["ksero"], english: "to know", category: "Verbs" },
  { word: "καταλαβαίνω", transliteration: "katalavaino", alternates: ["katalaveno"], english: "to understand", category: "Verbs" },
  { word: "δουλεύω", transliteration: "doulevo", alternates: ["dulevo"], english: "to work", category: "Verbs" },
  { word: "διαβάζω", transliteration: "diavazo", alternates: ["diawazo"], english: "to read / to study", category: "Verbs" },
  { word: "γράφω", transliteration: "grafo", alternates: [], english: "to write", category: "Verbs" },
  { word: "αγοράζω", transliteration: "agorazo", alternates: [], english: "to buy", category: "Verbs" },
  { word: "παίζω", transliteration: "paizo", alternates: ["pezo"], english: "to play", category: "Verbs" },
  { word: "τραγουδώ", transliteration: "tragudo", alternates: ["tragoudo"], english: "to sing", category: "Verbs" },
  { word: "τρέχω", transliteration: "trecho", alternates: ["treho"], english: "to run", category: "Verbs" },
  { word: "σκέφτομαι", transliteration: "skeftomai", alternates: [], english: "to think", category: "Verbs" },
  { word: "ζω", transliteration: "zo", alternates: [], english: "to live", category: "Verbs" },

  // Adjectives
  { word: "μεγάλος", transliteration: "megalos", alternates: [], english: "big / large", category: "Adjectives" },
  { word: "μικρός", transliteration: "mikros", alternates: [], english: "small / little", category: "Adjectives" },
  { word: "καλός", transliteration: "kalos", alternates: [], english: "good", category: "Adjectives" },
  { word: "κακός", transliteration: "kakos", alternates: [], english: "bad", category: "Adjectives" },
  { word: "ωραίος", transliteration: "oraios", alternates: ["oraeos"], english: "beautiful / nice", category: "Adjectives" },
  { word: "γρήγορος", transliteration: "grigoros", alternates: [], english: "fast / quick", category: "Adjectives" },
  { word: "αργός", transliteration: "argos", alternates: [], english: "slow", category: "Adjectives" },
  { word: "ζεστός", transliteration: "zestos", alternates: [], english: "warm / hot", category: "Adjectives" },
  { word: "κρύος", transliteration: "kryos", alternates: ["krios"], english: "cold", category: "Adjectives" },
  { word: "νέος", transliteration: "neos", alternates: [], english: "new / young", category: "Adjectives" },
  { word: "παλιός", transliteration: "palios", alternates: [], english: "old", category: "Adjectives" },
  { word: "ακριβός", transliteration: "akrivos", alternates: [], english: "expensive", category: "Adjectives" },
  { word: "φτηνός", transliteration: "ftinos", alternates: [], english: "cheap / inexpensive", category: "Adjectives" },
  { word: "δύσκολος", transliteration: "dyskolos", alternates: ["diskolos"], english: "difficult / hard", category: "Adjectives" },
  { word: "εύκολος", transliteration: "efkolos", alternates: ["evkolos"], english: "easy", category: "Adjectives" },

  // Places
  { word: "σπίτι", transliteration: "spiti", alternates: [], english: "house / home", category: "Places" },
  { word: "σχολείο", transliteration: "scholeio", alternates: ["sholeio"], english: "school", category: "Places" },
  { word: "εκκλησία", transliteration: "ekklisia", alternates: ["eklisia"], english: "church", category: "Places" },
  { word: "νοσοκομείο", transliteration: "nosokomeio", alternates: [], english: "hospital", category: "Places" },
  { word: "εστιατόριο", transliteration: "estiatorio", alternates: [], english: "restaurant", category: "Places" },
  { word: "ξενοδοχείο", transliteration: "xenodocheio", alternates: ["xenodohio"], english: "hotel", category: "Places" },
  { word: "αεροδρόμιο", transliteration: "aerodromio", alternates: [], english: "airport", category: "Places" },
  { word: "σταθμός", transliteration: "stathmos", alternates: [], english: "station", category: "Places" },
  { word: "πλατεία", transliteration: "plateia", alternates: [], english: "square / plaza", category: "Places" },
  { word: "παραλία", transliteration: "paralia", alternates: [], english: "beach", category: "Places" },
  { word: "βουνό", transliteration: "vouno", alternates: [], english: "mountain", category: "Places" },
  { word: "πάρκο", transliteration: "parko", alternates: [], english: "park", category: "Places" },
  { word: "πόλη", transliteration: "poli", alternates: [], english: "city", category: "Places" },
  { word: "χωριό", transliteration: "chorio", alternates: ["horio"], english: "village", category: "Places" },
  { word: "αγορά", transliteration: "agora", alternates: [], english: "market / agora", category: "Places" },

  // Animals
  { word: "σκύλος", transliteration: "skylos", alternates: ["skilos"], english: "dog", category: "Animals" },
  { word: "γάτα", transliteration: "gata", alternates: [], english: "cat", category: "Animals" },
  { word: "άλογο", transliteration: "alogo", alternates: [], english: "horse", category: "Animals" },
  { word: "αγελάδα", transliteration: "agelada", alternates: [], english: "cow", category: "Animals" },
  { word: "πρόβατο", transliteration: "provato", alternates: [], english: "sheep", category: "Animals" },
  { word: "πουλί", transliteration: "pouli", alternates: [], english: "bird", category: "Animals" },
  { word: "ελέφαντας", transliteration: "elefantas", alternates: [], english: "elephant", category: "Animals" },
  { word: "λιοντάρι", transliteration: "liontari", alternates: [], english: "lion", category: "Animals" },
  { word: "αρκούδα", transliteration: "arkouda", alternates: [], english: "bear", category: "Animals" },
  { word: "φίδι", transliteration: "fidi", alternates: [], english: "snake", category: "Animals" },

  // Nature
  { word: "ήλιος", transliteration: "ilios", alternates: ["ilios"], english: "sun", category: "Nature" },
  { word: "φεγγάρι", transliteration: "fengari", alternates: [], english: "moon", category: "Nature" },
  { word: "αστέρι", transliteration: "asteri", alternates: [], english: "star", category: "Nature" },
  { word: "ουρανός", transliteration: "ouranos", alternates: [], english: "sky / heaven", category: "Nature" },
  { word: "σύννεφο", transliteration: "synnevo", alternates: ["sinnevo"], english: "cloud", category: "Nature" },
  { word: "βροχή", transliteration: "vrochi", alternates: [], english: "rain", category: "Nature" },
  { word: "χιόνι", transliteration: "chioni", alternates: ["hioni"], english: "snow", category: "Nature" },
  { word: "άνεμος", transliteration: "anemos", alternates: [], english: "wind", category: "Nature" },
  { word: "θάλασσα", transliteration: "thalassa", alternates: ["halasa"], english: "sea", category: "Nature" },
  { word: "ποτάμι", transliteration: "potami", alternates: [], english: "river", category: "Nature" },
  { word: "δέντρο", transliteration: "dentro", alternates: [], english: "tree", category: "Nature" },
  { word: "λουλούδι", transliteration: "louloudi", alternates: [], english: "flower", category: "Nature" },
  { word: "δάσος", transliteration: "dasos", alternates: [], english: "forest", category: "Nature" },

  // Countries
  { word: "Ελλάδα", transliteration: "Ellada", alternates: ["ellada", "Hellas"], english: "Greece", category: "Countries" },
  { word: "Κύπρος", transliteration: "Kypros", alternates: ["kypros", "Kipros"], english: "Cyprus", category: "Countries" },
  { word: "Ιταλία", transliteration: "Italia", alternates: ["italia"], english: "Italy", category: "Countries" },
  { word: "Γερμανία", transliteration: "Germania", alternates: ["germania"], english: "Germany", category: "Countries" },
  { word: "Γαλλία", transliteration: "Gallia", alternates: ["gallia"], english: "France", category: "Countries" },
  { word: "Ισπανία", transliteration: "Ispania", alternates: ["ispania"], english: "Spain", category: "Countries" },
  { word: "Αμερική", transliteration: "Ameriki", alternates: ["ameriki"], english: "America", category: "Countries" },
  { word: "Αγγλία", transliteration: "Anglia", alternates: ["anglia"], english: "England", category: "Countries" },
  { word: "Τουρκία", transliteration: "Tourkia", alternates: ["tourkia"], english: "Turkey", category: "Countries" },
  { word: "Ρωσία", transliteration: "Rosia", alternates: ["rosia"], english: "Russia", category: "Countries" },

  // Time
  { word: "σήμερα", transliteration: "simera", alternates: ["himera"], english: "today", category: "Time" },
  { word: "χθες", transliteration: "chthes", alternates: ["hthes", "htes"], english: "yesterday", category: "Time" },
  { word: "αύριο", transliteration: "avrio", alternates: [], english: "tomorrow", category: "Time" },
  { word: "τώρα", transliteration: "tora", alternates: [], english: "now", category: "Time" },
  { word: "ώρα", transliteration: "ora", alternates: [], english: "hour / time", category: "Time" },
  { word: "λεπτό", transliteration: "lepto", alternates: [], english: "minute", category: "Time" },
  { word: "πρωί", transliteration: "proi", alternates: [], english: "morning", category: "Time" },
  { word: "μεσημέρι", transliteration: "mesimeri", alternates: [], english: "noon / midday", category: "Time" },
  { word: "βράδυ", transliteration: "vrady", alternates: ["vradi"], english: "evening", category: "Time" },
  { word: "νύχτα", transliteration: "nychta", alternates: ["nihta"], english: "night", category: "Time" },
  { word: "εβδομάδα", transliteration: "evdomada", alternates: [], english: "week", category: "Time" },
  { word: "χρόνος", transliteration: "chronos", alternates: ["hronos"], english: "year / time", category: "Time" },

  // Everyday
  { word: "άνθρωπος", transliteration: "anthropos", alternates: ["anthoropos"], english: "person / human", category: "Everyday" },
  { word: "ζωή", transliteration: "zoi", alternates: [], english: "life", category: "Everyday" },
  { word: "δουλειά", transliteration: "doulia", alternates: ["doulia"], english: "work / job", category: "Everyday" },
  { word: "χρήματα", transliteration: "chrimata", alternates: ["hrimata"], english: "money", category: "Everyday" },
  { word: "τηλέφωνο", transliteration: "tilefono", alternates: [], english: "telephone / phone", category: "Everyday" },
  { word: "υπολογιστής", transliteration: "ypologistis", alternates: ["ipologistis"], english: "computer", category: "Everyday" },
  { word: "αυτοκίνητο", transliteration: "aftokinito", alternates: ["avtokinito"], english: "car", category: "Everyday" },
  { word: "βιβλίο", transliteration: "vivlio", alternates: [], english: "book", category: "Everyday" },
  { word: "λέξη", transliteration: "lexi", alternates: [], english: "word", category: "Everyday" },
  { word: "γλώσσα", transliteration: "glossa", alternates: ["glosa"], english: "language / tongue", category: "Everyday" },
  { word: "ερώτηση", transliteration: "erotisi", alternates: [], english: "question", category: "Everyday" },
  { word: "φίλος", transliteration: "filos", alternates: [], english: "friend", category: "Everyday" },
  { word: "αγάπη", transliteration: "agapi", alternates: [], english: "love", category: "Everyday" },
  { word: "ευτυχία", transliteration: "eftychia", alternates: ["evtychia"], english: "happiness", category: "Everyday" },
  { word: "αλήθεια", transliteration: "alitheia", alternates: ["alithia"], english: "truth", category: "Everyday" },
  { word: "ελευθερία", transliteration: "eleftheria", alternates: ["eleftheria"], english: "freedom", category: "Everyday" },
  { word: "ειρήνη", transliteration: "eirini", alternates: ["irini"], english: "peace", category: "Everyday" },
];
