const WORDS = [
  // Greetings & Phrases
  { russian: "привет", transliteration: "privet", alternates: [], english: "hi / hello (informal)", category: "Greetings" },
  { russian: "здравствуйте", transliteration: "zdravstvuyte", alternates: ["zdravstvuyte", "zdravstvujte"], english: "hello (formal)", category: "Greetings" },
  { russian: "пока", transliteration: "poka", alternates: [], english: "bye (informal)", category: "Greetings" },
  { russian: "спасибо", transliteration: "spasibo", alternates: [], english: "thank you", category: "Greetings" },
  { russian: "пожалуйста", transliteration: "pozhaluysta", alternates: ["pozhaluista"], english: "please / you're welcome", category: "Greetings" },
  { russian: "да", transliteration: "da", alternates: [], english: "yes", category: "Greetings" },
  { russian: "нет", transliteration: "net", alternates: [], english: "no", category: "Greetings" },
  { russian: "извините", transliteration: "izvinite", alternates: ["izvinitye"], english: "excuse me / sorry", category: "Greetings" },
  { russian: "хорошо", transliteration: "khorosho", alternates: ["horosho"], english: "good / okay", category: "Greetings" },
  { russian: "до свидания", transliteration: "do svidaniya", alternates: ["do svidania"], english: "goodbye (formal)", category: "Greetings" },
  { russian: "добро пожаловать", transliteration: "dobro pozhalovat", alternates: [], english: "welcome", category: "Greetings" },

  // Numbers
  { russian: "один", transliteration: "odin", alternates: [], english: "one", category: "Numbers" },
  { russian: "два", transliteration: "dva", alternates: [], english: "two", category: "Numbers" },
  { russian: "три", transliteration: "tri", alternates: [], english: "three", category: "Numbers" },
  { russian: "четыре", transliteration: "chetyre", alternates: [], english: "four", category: "Numbers" },
  { russian: "пять", transliteration: "pyat", alternates: ["piat"], english: "five", category: "Numbers" },
  { russian: "шесть", transliteration: "shest", alternates: [], english: "six", category: "Numbers" },
  { russian: "семь", transliteration: "sem", alternates: [], english: "seven", category: "Numbers" },
  { russian: "восемь", transliteration: "vosem", alternates: [], english: "eight", category: "Numbers" },
  { russian: "девять", transliteration: "devyat", alternates: ["deviat"], english: "nine", category: "Numbers" },
  { russian: "десять", transliteration: "desyat", alternates: ["desiat"], english: "ten", category: "Numbers" },
  { russian: "одиннадцать", transliteration: "odinnadtsat", alternates: [], english: "eleven", category: "Numbers" },
  { russian: "двенадцать", transliteration: "dvenadtsat", alternates: [], english: "twelve", category: "Numbers" },
  { russian: "двадцать", transliteration: "dvadtsat", alternates: [], english: "twenty", category: "Numbers" },
  { russian: "сто", transliteration: "sto", alternates: [], english: "one hundred", category: "Numbers" },
  { russian: "тысяча", transliteration: "tysyacha", alternates: ["tysiача", "tysiаcha"], english: "one thousand", category: "Numbers" },

  // Days of the Week
  { russian: "понедельник", transliteration: "ponedelnik", alternates: ["ponedelnik"], english: "Monday", category: "Days" },
  { russian: "вторник", transliteration: "vtornik", alternates: [], english: "Tuesday", category: "Days" },
  { russian: "среда", transliteration: "sreda", alternates: [], english: "Wednesday", category: "Days" },
  { russian: "четверг", transliteration: "chetverg", alternates: [], english: "Thursday", category: "Days" },
  { russian: "пятница", transliteration: "pyatnitsa", alternates: ["piatnitsa"], english: "Friday", category: "Days" },
  { russian: "суббота", transliteration: "subbota", alternates: [], english: "Saturday", category: "Days" },
  { russian: "воскресенье", transliteration: "voskresenye", alternates: ["voskresenije", "voskreseniye"], english: "Sunday", category: "Days" },

  // Months
  { russian: "январь", transliteration: "yanvar", alternates: ["ianvar"], english: "January", category: "Months" },
  { russian: "февраль", transliteration: "fevral", alternates: [], english: "February", category: "Months" },
  { russian: "март", transliteration: "mart", alternates: [], english: "March", category: "Months" },
  { russian: "апрель", transliteration: "aprel", alternates: [], english: "April", category: "Months" },
  { russian: "май", transliteration: "may", alternates: ["mai", "maj"], english: "May", category: "Months" },
  { russian: "июнь", transliteration: "iyun", alternates: ["iun", "ijun"], english: "June", category: "Months" },
  { russian: "июль", transliteration: "iyul", alternates: ["iul", "ijul"], english: "July", category: "Months" },
  { russian: "август", transliteration: "avgust", alternates: [], english: "August", category: "Months" },
  { russian: "сентябрь", transliteration: "sentyabr", alternates: ["sentiabr"], english: "September", category: "Months" },
  { russian: "октябрь", transliteration: "oktyabr", alternates: ["oktiabr"], english: "October", category: "Months" },
  { russian: "ноябрь", transliteration: "noyabr", alternates: ["noiabr"], english: "November", category: "Months" },
  { russian: "декабрь", transliteration: "dekabr", alternates: [], english: "December", category: "Months" },

  // Family
  { russian: "мама", transliteration: "mama", alternates: [], english: "mom", category: "Family" },
  { russian: "папа", transliteration: "papa", alternates: [], english: "dad", category: "Family" },
  { russian: "мать", transliteration: "mat", alternates: ["mat'"], english: "mother", category: "Family" },
  { russian: "отец", transliteration: "otets", alternates: [], english: "father", category: "Family" },
  { russian: "брат", transliteration: "brat", alternates: [], english: "brother", category: "Family" },
  { russian: "сестра", transliteration: "sestra", alternates: [], english: "sister", category: "Family" },
  { russian: "сын", transliteration: "syn", alternates: ["sin"], english: "son", category: "Family" },
  { russian: "дочь", transliteration: "doch", alternates: ["doch'"], english: "daughter", category: "Family" },
  { russian: "дедушка", transliteration: "dedushka", alternates: [], english: "grandfather", category: "Family" },
  { russian: "бабушка", transliteration: "babushka", alternates: [], english: "grandmother", category: "Family" },
  { russian: "дядя", transliteration: "dyadya", alternates: ["diadiа", "dyadya"], english: "uncle", category: "Family" },
  { russian: "тётя", transliteration: "tyotya", alternates: ["tiotia", "tyotia"], english: "aunt", category: "Family" },
  { russian: "муж", transliteration: "muzh", alternates: [], english: "husband", category: "Family" },
  { russian: "жена", transliteration: "zhena", alternates: [], english: "wife", category: "Family" },
  { russian: "ребёнок", transliteration: "rebyonok", alternates: ["rebenok", "rebionok"], english: "child", category: "Family" },
  { russian: "семья", transliteration: "semya", alternates: ["semia"], english: "family", category: "Family" },

  // Colors
  { russian: "красный", transliteration: "krasny", alternates: ["krasnyy", "krasnyi"], english: "red", category: "Colors" },
  { russian: "синий", transliteration: "siniy", alternates: ["siny", "sinij"], english: "blue (dark)", category: "Colors" },
  { russian: "зелёный", transliteration: "zelony", alternates: ["zelyony", "zelonyy", "zelyonyy"], english: "green", category: "Colors" },
  { russian: "жёлтый", transliteration: "zholty", alternates: ["zhelty", "zholtyy", "zheltyy"], english: "yellow", category: "Colors" },
  { russian: "белый", transliteration: "bely", alternates: ["belyy", "belyi"], english: "white", category: "Colors" },
  { russian: "чёрный", transliteration: "chorny", alternates: ["cherny", "chornyy", "chernyy"], english: "black", category: "Colors" },
  { russian: "оранжевый", transliteration: "oranzhevyy", alternates: ["oranzheviy", "oranzheviy"], english: "orange", category: "Colors" },
  { russian: "фиолетовый", transliteration: "fioletovyy", alternates: ["fioletovy", "fioletoviy"], english: "purple / violet", category: "Colors" },
  { russian: "розовый", transliteration: "rozovyy", alternates: ["rozovy", "rozoviy"], english: "pink", category: "Colors" },
  { russian: "коричневый", transliteration: "korichnevyy", alternates: ["korichnevy", "korichneviy"], english: "brown", category: "Colors" },
  { russian: "серый", transliteration: "sery", alternates: ["seryy", "seryi"], english: "grey / gray", category: "Colors" },
  { russian: "голубой", transliteration: "goluboy", alternates: ["goluboj"], english: "light blue / sky blue", category: "Colors" },

  // Food & Drink
  { russian: "хлеб", transliteration: "khleb", alternates: ["hleb"], english: "bread", category: "Food & Drink" },
  { russian: "вода", transliteration: "voda", alternates: [], english: "water", category: "Food & Drink" },
  { russian: "молоко", transliteration: "moloko", alternates: [], english: "milk", category: "Food & Drink" },
  { russian: "мясо", transliteration: "myaso", alternates: ["miaso"], english: "meat", category: "Food & Drink" },
  { russian: "рыба", transliteration: "ryba", alternates: ["riba"], english: "fish", category: "Food & Drink" },
  { russian: "яблоко", transliteration: "yabloko", alternates: ["iabloko"], english: "apple", category: "Food & Drink" },
  { russian: "банан", transliteration: "banan", alternates: [], english: "banana", category: "Food & Drink" },
  { russian: "суп", transliteration: "sup", alternates: [], english: "soup", category: "Food & Drink" },
  { russian: "салат", transliteration: "salat", alternates: [], english: "salad", category: "Food & Drink" },
  { russian: "чай", transliteration: "chay", alternates: ["chai", "chaj"], english: "tea", category: "Food & Drink" },
  { russian: "кофе", transliteration: "kofe", alternates: [], english: "coffee", category: "Food & Drink" },
  { russian: "пиво", transliteration: "pivo", alternates: [], english: "beer", category: "Food & Drink" },
  { russian: "вино", transliteration: "vino", alternates: [], english: "wine", category: "Food & Drink" },
  { russian: "сыр", transliteration: "syr", alternates: ["sir"], english: "cheese", category: "Food & Drink" },
  { russian: "масло", transliteration: "maslo", alternates: [], english: "butter / oil", category: "Food & Drink" },
  { russian: "яйцо", transliteration: "yaytso", alternates: ["iaitso", "yaitso"], english: "egg", category: "Food & Drink" },
  { russian: "курица", transliteration: "kuritsa", alternates: [], english: "chicken", category: "Food & Drink" },
  { russian: "картофель", transliteration: "kartofel", alternates: ["kartofel'"], english: "potato", category: "Food & Drink" },
  { russian: "помидор", transliteration: "pomidor", alternates: [], english: "tomato", category: "Food & Drink" },
  { russian: "лук", transliteration: "luk", alternates: [], english: "onion", category: "Food & Drink" },
  { russian: "морковь", transliteration: "morkov", alternates: ["morkov'", "morkovj"], english: "carrot", category: "Food & Drink" },
  { russian: "рис", transliteration: "ris", alternates: [], english: "rice", category: "Food & Drink" },
  { russian: "борщ", transliteration: "borshch", alternates: ["borsch", "borscht"], english: "borscht (beet soup)", category: "Food & Drink" },
  { russian: "пельмени", transliteration: "pelmeni", alternates: [], english: "dumplings", category: "Food & Drink" },
  { russian: "сахар", transliteration: "sakhar", alternates: ["sahar"], english: "sugar", category: "Food & Drink" },
  { russian: "соль", transliteration: "sol", alternates: ["sol'"], english: "salt", category: "Food & Drink" },
  { russian: "овощи", transliteration: "ovoshchi", alternates: ["ovoschi", "ovoshchi"], english: "vegetables", category: "Food & Drink" },
  { russian: "фрукты", transliteration: "frukty", alternates: [], english: "fruits", category: "Food & Drink" },

  // Body Parts
  { russian: "голова", transliteration: "golova", alternates: [], english: "head", category: "Body" },
  { russian: "лицо", transliteration: "litso", alternates: [], english: "face", category: "Body" },
  { russian: "глаз", transliteration: "glaz", alternates: [], english: "eye", category: "Body" },
  { russian: "ухо", transliteration: "ukho", alternates: ["ukho", "uho"], english: "ear", category: "Body" },
  { russian: "нос", transliteration: "nos", alternates: [], english: "nose", category: "Body" },
  { russian: "рот", transliteration: "rot", alternates: [], english: "mouth", category: "Body" },
  { russian: "рука", transliteration: "ruka", alternates: [], english: "hand / arm", category: "Body" },
  { russian: "нога", transliteration: "noga", alternates: [], english: "leg / foot", category: "Body" },
  { russian: "сердце", transliteration: "serdtse", alternates: ["serdce"], english: "heart", category: "Body" },
  { russian: "спина", transliteration: "spina", alternates: [], english: "back", category: "Body" },
  { russian: "живот", transliteration: "zhivot", alternates: [], english: "stomach / belly", category: "Body" },
  { russian: "зуб", transliteration: "zub", alternates: [], english: "tooth", category: "Body" },
  { russian: "волосы", transliteration: "volosy", alternates: [], english: "hair", category: "Body" },
  { russian: "шея", transliteration: "sheya", alternates: ["sheia"], english: "neck", category: "Body" },
  { russian: "плечо", transliteration: "plecho", alternates: [], english: "shoulder", category: "Body" },
  { russian: "колено", transliteration: "koleno", alternates: [], english: "knee", category: "Body" },

  // Verbs
  { russian: "говорить", transliteration: "govorit", alternates: ["govorit'"], english: "to speak", category: "Verbs" },
  { russian: "слушать", transliteration: "slushat", alternates: ["slushat'"], english: "to listen", category: "Verbs" },
  { russian: "читать", transliteration: "chitat", alternates: ["chitat'"], english: "to read", category: "Verbs" },
  { russian: "писать", transliteration: "pisat", alternates: ["pisat'"], english: "to write", category: "Verbs" },
  { russian: "идти", transliteration: "idti", alternates: [], english: "to go (on foot)", category: "Verbs" },
  { russian: "есть", transliteration: "yest", alternates: ["est", "yest'"], english: "to eat", category: "Verbs" },
  { russian: "пить", transliteration: "pit", alternates: ["pit'", "peet"], english: "to drink", category: "Verbs" },
  { russian: "спать", transliteration: "spat", alternates: ["spat'"], english: "to sleep", category: "Verbs" },
  { russian: "работать", transliteration: "rabotat", alternates: ["rabotat'"], english: "to work", category: "Verbs" },
  { russian: "учиться", transliteration: "uchitsya", alternates: ["uchitsia"], english: "to study / to learn", category: "Verbs" },
  { russian: "любить", transliteration: "lyubit", alternates: ["lubit", "lyubit'"], english: "to love", category: "Verbs" },
  { russian: "хотеть", transliteration: "khotet", alternates: ["hotet", "khotet'"], english: "to want", category: "Verbs" },
  { russian: "знать", transliteration: "znat", alternates: ["znat'"], english: "to know", category: "Verbs" },
  { russian: "видеть", transliteration: "videt", alternates: ["videt'"], english: "to see", category: "Verbs" },
  { russian: "делать", transliteration: "delat", alternates: ["delat'"], english: "to do / to make", category: "Verbs" },
  { russian: "давать", transliteration: "davat", alternates: ["davat'"], english: "to give", category: "Verbs" },
  { russian: "жить", transliteration: "zhit", alternates: ["zhit'"], english: "to live", category: "Verbs" },
  { russian: "думать", transliteration: "dumat", alternates: ["dumat'"], english: "to think", category: "Verbs" },
  { russian: "понимать", transliteration: "ponimat", alternates: ["poniimat", "ponimat'"], english: "to understand", category: "Verbs" },
  { russian: "покупать", transliteration: "pokupat", alternates: ["pokupat'"], english: "to buy", category: "Verbs" },
  { russian: "помогать", transliteration: "pomogat", alternates: ["pomogat'"], english: "to help", category: "Verbs" },
  { russian: "открывать", transliteration: "otkryvat", alternates: ["otkryvat'"], english: "to open", category: "Verbs" },
  { russian: "закрывать", transliteration: "zakryvat", alternates: ["zakryvat'"], english: "to close", category: "Verbs" },
  { russian: "искать", transliteration: "iskat", alternates: ["iskat'"], english: "to search / to look for", category: "Verbs" },
  { russian: "находить", transliteration: "nakhodit", alternates: ["nakhodit'", "nahodit"], english: "to find", category: "Verbs" },
  { russian: "начинать", transliteration: "nachinat", alternates: ["nachinat'"], english: "to begin / to start", category: "Verbs" },
  { russian: "ждать", transliteration: "zhdat", alternates: ["zhdat'"], english: "to wait", category: "Verbs" },
  { russian: "смотреть", transliteration: "smotret", alternates: ["smotret'"], english: "to watch / to look", category: "Verbs" },
  { russian: "слышать", transliteration: "slyshat", alternates: ["slyshat'"], english: "to hear", category: "Verbs" },
  { russian: "бежать", transliteration: "bezhat", alternates: ["bezhat'"], english: "to run", category: "Verbs" },
  { russian: "играть", transliteration: "igrat", alternates: ["igrat'"], english: "to play", category: "Verbs" },
  { russian: "петь", transliteration: "pet", alternates: ["pet'"], english: "to sing", category: "Verbs" },
  { russian: "платить", transliteration: "platit", alternates: ["platit'"], english: "to pay", category: "Verbs" },
  { russian: "получать", transliteration: "poluchat", alternates: ["poluchat'"], english: "to receive / to get", category: "Verbs" },
  { russian: "забывать", transliteration: "zabyvat", alternates: ["zabyvat'"], english: "to forget", category: "Verbs" },

  // Adjectives
  { russian: "большой", transliteration: "bolshoy", alternates: ["bolshoj", "bolshoi"], english: "big / large", category: "Adjectives" },
  { russian: "маленький", transliteration: "malenky", alternates: ["malenkiy", "malenkij", "malenkii"], english: "small / little", category: "Adjectives" },
  { russian: "хороший", transliteration: "khoroshy", alternates: ["khoroshiy", "khoroshij", "khorosii", "horoshy"], english: "good", category: "Adjectives" },
  { russian: "плохой", transliteration: "plokhoy", alternates: ["plokhoj", "plohoy"], english: "bad", category: "Adjectives" },
  { russian: "новый", transliteration: "novy", alternates: ["novyy", "novyi"], english: "new", category: "Adjectives" },
  { russian: "старый", transliteration: "stary", alternates: ["staryy", "staryi"], english: "old", category: "Adjectives" },
  { russian: "красивый", transliteration: "krasivyy", alternates: ["krasivy", "krasiviy"], english: "beautiful / handsome", category: "Adjectives" },
  { russian: "умный", transliteration: "umny", alternates: ["umnyy", "umnyi"], english: "smart / clever", category: "Adjectives" },
  { russian: "быстрый", transliteration: "bystry", alternates: ["bystryy", "bystryi"], english: "fast / quick", category: "Adjectives" },
  { russian: "медленный", transliteration: "medlenny", alternates: ["medlennyy", "medlennyi"], english: "slow", category: "Adjectives" },
  { russian: "дорогой", transliteration: "dorogoy", alternates: ["dorogoj"], english: "expensive / dear", category: "Adjectives" },
  { russian: "дешёвый", transliteration: "deshyovy", alternates: ["deshovy", "deshoviy", "deshevyy"], english: "cheap / inexpensive", category: "Adjectives" },
  { russian: "горячий", transliteration: "goryachy", alternates: ["goryachiy", "goriaciy"], english: "hot", category: "Adjectives" },
  { russian: "холодный", transliteration: "kholodny", alternates: ["holodny", "kholodnyy"], english: "cold", category: "Adjectives" },
  { russian: "тёплый", transliteration: "tyoply", alternates: ["tyoplyy", "tioply", "teply"], english: "warm", category: "Adjectives" },
  { russian: "интересный", transliteration: "interesny", alternates: ["interesnyy", "interesnyi"], english: "interesting", category: "Adjectives" },
  { russian: "лёгкий", transliteration: "lyogky", alternates: ["lyogkiy", "lyogkij", "legky"], english: "easy / light", category: "Adjectives" },
  { russian: "трудный", transliteration: "trudny", alternates: ["trudnyy", "trudnyi"], english: "difficult / hard", category: "Adjectives" },
  { russian: "молодой", transliteration: "molodoy", alternates: ["molodoj"], english: "young", category: "Adjectives" },
  { russian: "высокий", transliteration: "vysokiy", alternates: ["vysokij", "visoky"], english: "tall / high", category: "Adjectives" },
  { russian: "низкий", transliteration: "nizky", alternates: ["nizkiy", "nizkij"], english: "low / short", category: "Adjectives" },
  { russian: "длинный", transliteration: "dlinny", alternates: ["dlinnyy", "dlinnyi"], english: "long", category: "Adjectives" },
  { russian: "короткий", transliteration: "korotky", alternates: ["korotkiy", "korotkij"], english: "short (length)", category: "Adjectives" },
  { russian: "чистый", transliteration: "chisty", alternates: ["chistyy", "chistyi"], english: "clean / pure", category: "Adjectives" },
  { russian: "грязный", transliteration: "gryazny", alternates: ["griazny", "gryaznyy"], english: "dirty", category: "Adjectives" },
  { russian: "тихий", transliteration: "tikhy", alternates: ["tikhiy", "tikhij"], english: "quiet", category: "Adjectives" },
  { russian: "громкий", transliteration: "gromky", alternates: ["gromkiy", "gromkij"], english: "loud", category: "Adjectives" },
  { russian: "вкусный", transliteration: "vkusny", alternates: ["vkusnyy", "vkusnyi"], english: "tasty / delicious", category: "Adjectives" },
  { russian: "свежий", transliteration: "svezhiy", alternates: ["svezhy", "svezhij"], english: "fresh", category: "Adjectives" },
  { russian: "прямой", transliteration: "pryamoy", alternates: ["priamoy", "pryamoj"], english: "straight / direct", category: "Adjectives" },

  // Places
  { russian: "дом", transliteration: "dom", alternates: [], english: "house / home", category: "Places" },
  { russian: "школа", transliteration: "shkola", alternates: [], english: "school", category: "Places" },
  { russian: "университет", transliteration: "universitet", alternates: [], english: "university", category: "Places" },
  { russian: "магазин", transliteration: "magazin", alternates: [], english: "shop / store", category: "Places" },
  { russian: "ресторан", transliteration: "restoran", alternates: [], english: "restaurant", category: "Places" },
  { russian: "больница", transliteration: "bolnitsa", alternates: [], english: "hospital", category: "Places" },
  { russian: "банк", transliteration: "bank", alternates: [], english: "bank", category: "Places" },
  { russian: "аптека", transliteration: "apteka", alternates: [], english: "pharmacy", category: "Places" },
  { russian: "улица", transliteration: "ulitsa", alternates: [], english: "street", category: "Places" },
  { russian: "парк", transliteration: "park", alternates: [], english: "park", category: "Places" },
  { russian: "город", transliteration: "gorod", alternates: [], english: "city / town", category: "Places" },
  { russian: "страна", transliteration: "strana", alternates: [], english: "country", category: "Places" },
  { russian: "театр", transliteration: "teatr", alternates: [], english: "theater / theatre", category: "Places" },
  { russian: "музей", transliteration: "muzey", alternates: ["muzej"], english: "museum", category: "Places" },
  { russian: "библиотека", transliteration: "biblioteka", alternates: [], english: "library", category: "Places" },
  { russian: "офис", transliteration: "ofis", alternates: [], english: "office", category: "Places" },
  { russian: "рынок", transliteration: "rynok", alternates: ["rinok"], english: "market", category: "Places" },
  { russian: "гостиница", transliteration: "gostinitsa", alternates: [], english: "hotel", category: "Places" },
  { russian: "аэропорт", transliteration: "aeroport", alternates: [], english: "airport", category: "Places" },
  { russian: "вокзал", transliteration: "vokzal", alternates: [], english: "train station", category: "Places" },
  { russian: "метро", transliteration: "metro", alternates: [], english: "metro / subway", category: "Places" },
  { russian: "площадь", transliteration: "ploshchad", alternates: ["ploshchad'", "ploshad"], english: "square / plaza", category: "Places" },
  { russian: "почта", transliteration: "pochta", alternates: [], english: "post office / mail", category: "Places" },
  { russian: "церковь", transliteration: "tserkov", alternates: ["cerkov", "tserkov'"], english: "church", category: "Places" },

  // Animals
  { russian: "кошка", transliteration: "koshka", alternates: [], english: "cat", category: "Animals" },
  { russian: "собака", transliteration: "sobaka", alternates: [], english: "dog", category: "Animals" },
  { russian: "птица", transliteration: "ptitsa", alternates: [], english: "bird", category: "Animals" },
  { russian: "лошадь", transliteration: "loshad", alternates: ["loshad'"], english: "horse", category: "Animals" },
  { russian: "корова", transliteration: "korova", alternates: [], english: "cow", category: "Animals" },
  { russian: "свинья", transliteration: "svinya", alternates: ["svinia"], english: "pig", category: "Animals" },
  { russian: "медведь", transliteration: "medved", alternates: ["medved'", "medvied"], english: "bear", category: "Animals" },
  { russian: "волк", transliteration: "volk", alternates: [], english: "wolf", category: "Animals" },
  { russian: "лиса", transliteration: "lisa", alternates: [], english: "fox", category: "Animals" },
  { russian: "заяц", transliteration: "zayats", alternates: ["zaiats"], english: "hare / rabbit", category: "Animals" },
  { russian: "мышь", transliteration: "mysh", alternates: ["mysh'", "mish"], english: "mouse", category: "Animals" },
  { russian: "змея", transliteration: "zmeya", alternates: ["zmeia"], english: "snake", category: "Animals" },
  { russian: "рыба", transliteration: "ryba", alternates: ["riba"], english: "fish", category: "Animals" },
  { russian: "орёл", transliteration: "oryol", alternates: ["oriol", "orel"], english: "eagle", category: "Animals" },

  // Nature & Weather
  { russian: "погода", transliteration: "pogoda", alternates: [], english: "weather", category: "Nature" },
  { russian: "солнце", transliteration: "solntse", alternates: ["solnce"], english: "sun", category: "Nature" },
  { russian: "дождь", transliteration: "dozhd", alternates: ["dozhd'", "doshd"], english: "rain", category: "Nature" },
  { russian: "снег", transliteration: "sneg", alternates: [], english: "snow", category: "Nature" },
  { russian: "ветер", transliteration: "veter", alternates: [], english: "wind", category: "Nature" },
  { russian: "облако", transliteration: "oblako", alternates: [], english: "cloud", category: "Nature" },
  { russian: "небо", transliteration: "nebo", alternates: [], english: "sky", category: "Nature" },
  { russian: "море", transliteration: "more", alternates: [], english: "sea", category: "Nature" },
  { russian: "река", transliteration: "reka", alternates: [], english: "river", category: "Nature" },
  { russian: "лес", transliteration: "les", alternates: [], english: "forest", category: "Nature" },
  { russian: "гора", transliteration: "gora", alternates: [], english: "mountain", category: "Nature" },
  { russian: "озеро", transliteration: "ozero", alternates: [], english: "lake", category: "Nature" },
  { russian: "земля", transliteration: "zemlya", alternates: ["zemlia"], english: "earth / land / soil", category: "Nature" },
  { russian: "цветок", transliteration: "tsvetok", alternates: ["cvetok"], english: "flower", category: "Nature" },
  { russian: "дерево", transliteration: "derevo", alternates: [], english: "tree", category: "Nature" },
  { russian: "трава", transliteration: "trava", alternates: [], english: "grass", category: "Nature" },

  // Countries & Cities
  { russian: "Россия", transliteration: "Rossiya", alternates: ["rossiya", "Russia", "russia"], english: "Russia", category: "Countries" },
  { russian: "Германия", transliteration: "Germaniya", alternates: ["germaniya", "Germaniia"], english: "Germany", category: "Countries" },
  { russian: "Франция", transliteration: "Frantsiya", alternates: ["frantsiya", "Frantsiia"], english: "France", category: "Countries" },
  { russian: "Испания", transliteration: "Ispaniya", alternates: ["ispaniya", "Ispaniia"], english: "Spain", category: "Countries" },
  { russian: "Италия", transliteration: "Italiya", alternates: ["italiya", "Italiia"], english: "Italy", category: "Countries" },
  { russian: "Китай", transliteration: "Kitay", alternates: ["kitay", "Kitaj"], english: "China", category: "Countries" },
  { russian: "Япония", transliteration: "Yaponiya", alternates: ["yaponiya", "Yaponiia"], english: "Japan", category: "Countries" },
  { russian: "Англия", transliteration: "Angliya", alternates: ["angliya", "Angliia"], english: "England", category: "Countries" },
  { russian: "Украина", transliteration: "Ukraina", alternates: ["ukraina"], english: "Ukraine", category: "Countries" },
  { russian: "Америка", transliteration: "Amerika", alternates: ["amerika"], english: "America", category: "Countries" },
  { russian: "Москва", transliteration: "Moskva", alternates: ["moskva"], english: "Moscow", category: "Countries" },
  { russian: "Лондон", transliteration: "London", alternates: ["london"], english: "London", category: "Countries" },
  { russian: "Париж", transliteration: "Parizh", alternates: ["parizh"], english: "Paris", category: "Countries" },

  // Time
  { russian: "время", transliteration: "vremya", alternates: ["vremia"], english: "time", category: "Time" },
  { russian: "час", transliteration: "chas", alternates: [], english: "hour", category: "Time" },
  { russian: "минута", transliteration: "minuta", alternates: [], english: "minute", category: "Time" },
  { russian: "день", transliteration: "den", alternates: ["den'"], english: "day", category: "Time" },
  { russian: "неделя", transliteration: "nedelya", alternates: ["nedelia"], english: "week", category: "Time" },
  { russian: "месяц", transliteration: "mesyats", alternates: ["mesiats", "mesiac"], english: "month", category: "Time" },
  { russian: "год", transliteration: "god", alternates: [], english: "year", category: "Time" },
  { russian: "утро", transliteration: "utro", alternates: [], english: "morning", category: "Time" },
  { russian: "вечер", transliteration: "vecher", alternates: [], english: "evening", category: "Time" },
  { russian: "ночь", transliteration: "noch", alternates: ["noch'"], english: "night", category: "Time" },
  { russian: "сегодня", transliteration: "segodnya", alternates: ["segoдnia", "segodnia"], english: "today", category: "Time" },
  { russian: "завтра", transliteration: "zavtra", alternates: [], english: "tomorrow", category: "Time" },
  { russian: "вчера", transliteration: "vchera", alternates: [], english: "yesterday", category: "Time" },
  { russian: "сейчас", transliteration: "seychas", alternates: ["seichas", "sejchas"], english: "now / right now", category: "Time" },
  { russian: "всегда", transliteration: "vsegda", alternates: [], english: "always", category: "Time" },
  { russian: "никогда", transliteration: "nikogda", alternates: [], english: "never", category: "Time" },
  { russian: "иногда", transliteration: "inogda", alternates: [], english: "sometimes", category: "Time" },

  // Everyday Life
  { russian: "человек", transliteration: "chelovek", alternates: [], english: "person / human", category: "Everyday" },
  { russian: "жизнь", transliteration: "zhizn", alternates: ["zhizn'"], english: "life", category: "Everyday" },
  { russian: "работа", transliteration: "rabota", alternates: [], english: "work / job", category: "Everyday" },
  { russian: "деньги", transliteration: "dengi", alternates: [], english: "money", category: "Everyday" },
  { russian: "телефон", transliteration: "telefon", alternates: [], english: "telephone / phone", category: "Everyday" },
  { russian: "компьютер", transliteration: "kompyuter", alternates: ["komputer", "kompiuter"], english: "computer", category: "Everyday" },
  { russian: "машина", transliteration: "mashina", alternates: [], english: "car / machine", category: "Everyday" },
  { russian: "книга", transliteration: "kniga", alternates: [], english: "book", category: "Everyday" },
  { russian: "слово", transliteration: "slovo", alternates: [], english: "word", category: "Everyday" },
  { russian: "язык", transliteration: "yazyk", alternates: ["iazyk"], english: "language / tongue", category: "Everyday" },
  { russian: "вопрос", transliteration: "vopros", alternates: [], english: "question", category: "Everyday" },
  { russian: "ответ", transliteration: "otvet", alternates: [], english: "answer / reply", category: "Everyday" },
  { russian: "имя", transliteration: "imya", alternates: ["imia"], english: "name (first name)", category: "Everyday" },
  { russian: "друг", transliteration: "drug", alternates: [], english: "friend", category: "Everyday" },
  { russian: "любовь", transliteration: "lyubov", alternates: ["lubov", "lyubov'"], english: "love", category: "Everyday" },
  { russian: "счастье", transliteration: "schastye", alternates: ["schastie", "shchastye"], english: "happiness", category: "Everyday" },
  { russian: "правда", transliteration: "pravda", alternates: [], english: "truth", category: "Everyday" },
  { russian: "свобода", transliteration: "svoboda", alternates: [], english: "freedom", category: "Everyday" },
  { russian: "мечта", transliteration: "mechta", alternates: [], english: "dream", category: "Everyday" },
  { russian: "надежда", transliteration: "nadezhda", alternates: [], english: "hope", category: "Everyday" },
  { russian: "проблема", transliteration: "problema", alternates: [], english: "problem", category: "Everyday" },
  { russian: "мир", transliteration: "mir", alternates: [], english: "world / peace", category: "Everyday" },
  { russian: "сила", transliteration: "sila", alternates: [], english: "strength / force", category: "Everyday" },
  { russian: "закон", transliteration: "zakon", alternates: [], english: "law", category: "Everyday" },
  { russian: "право", transliteration: "pravo", alternates: [], english: "right (legal) / law", category: "Everyday" },

  // Home
  { russian: "дверь", transliteration: "dver", alternates: ["dver'"], english: "door", category: "Home" },
  { russian: "окно", transliteration: "okno", alternates: [], english: "window", category: "Home" },
  { russian: "стол", transliteration: "stol", alternates: [], english: "table", category: "Home" },
  { russian: "стул", transliteration: "stul", alternates: [], english: "chair", category: "Home" },
  { russian: "кровать", transliteration: "krovat", alternates: ["krovat'"], english: "bed", category: "Home" },
  { russian: "диван", transliteration: "divan", alternates: [], english: "sofa / couch", category: "Home" },
  { russian: "кухня", transliteration: "kukhnya", alternates: ["kuhnya", "kukhnia"], english: "kitchen", category: "Home" },
  { russian: "ванная", transliteration: "vannaya", alternates: ["vannia", "vannaia"], english: "bathroom", category: "Home" },
  { russian: "пол", transliteration: "pol", alternates: [], english: "floor", category: "Home" },
  { russian: "потолок", transliteration: "potolok", alternates: [], english: "ceiling", category: "Home" },
  { russian: "стена", transliteration: "stena", alternates: [], english: "wall", category: "Home" },
  { russian: "квартира", transliteration: "kvartira", alternates: [], english: "apartment / flat", category: "Home" },
  { russian: "комната", transliteration: "komnata", alternates: [], english: "room", category: "Home" },
  { russian: "лампа", transliteration: "lampa", alternates: [], english: "lamp", category: "Home" },

  // Transport & Travel
  { russian: "автобус", transliteration: "avtobus", alternates: [], english: "bus", category: "Transport" },
  { russian: "поезд", transliteration: "poyezd", alternates: ["pojezd", "poiеzd"], english: "train", category: "Transport" },
  { russian: "самолёт", transliteration: "samolyot", alternates: ["samolet", "samolyot"], english: "airplane", category: "Transport" },
  { russian: "корабль", transliteration: "korabl", alternates: ["korabl'"], english: "ship", category: "Transport" },
  { russian: "такси", transliteration: "taksi", alternates: [], english: "taxi", category: "Transport" },
  { russian: "велосипед", transliteration: "velosiped", alternates: [], english: "bicycle", category: "Transport" },
  { russian: "дорога", transliteration: "doroga", alternates: [], english: "road / way", category: "Transport" },
  { russian: "билет", transliteration: "bilet", alternates: [], english: "ticket", category: "Transport" },
  { russian: "паспорт", transliteration: "pasport", alternates: [], english: "passport", category: "Transport" },
  { russian: "карта", transliteration: "karta", alternates: [], english: "map / card", category: "Transport" },

  // Media & Technology
  { russian: "газета", transliteration: "gazeta", alternates: [], english: "newspaper", category: "Media" },
  { russian: "журнал", transliteration: "zhurnal", alternates: [], english: "magazine / journal", category: "Media" },
  { russian: "радио", transliteration: "radio", alternates: [], english: "radio", category: "Media" },
  { russian: "телевизор", transliteration: "televizor", alternates: [], english: "television / TV", category: "Media" },
  { russian: "интернет", transliteration: "internet", alternates: [], english: "internet", category: "Media" },
  { russian: "сайт", transliteration: "sayt", alternates: ["sait", "sajt"], english: "website", category: "Media" },
  { russian: "письмо", transliteration: "pismo", alternates: ["pis'mo"], english: "letter", category: "Media" },
  { russian: "фото", transliteration: "foto", alternates: [], english: "photo", category: "Media" },
  { russian: "видео", transliteration: "video", alternates: [], english: "video", category: "Media" },
  { russian: "музыка", transliteration: "muzyka", alternates: ["muzika"], english: "music", category: "Media" },
  { russian: "кино", transliteration: "kino", alternates: [], english: "cinema / film", category: "Media" },
  { russian: "фильм", transliteration: "film", alternates: [], english: "film / movie", category: "Media" },
];
